---
layout: default
title: Heart rate detection
nav_order: 2
parent: /sleep/sleep_tracking.html
---

:toc:

== What it does
*Enhances your sleep tracking data and awake detection.*

If you have a compatible heart rate sensor, you can use it to:

. Gather your heart rate during the night and show it on your sleep graph
. Have much more precise awake detection

== Where to find it

[horizontal]
Enable HR monitoring for fully integrated devices::
  _Settings -> Wearables -> Heart rate monitoring_
  This regards all devices that we explicitly integrated, such as Pebble, Mi Band, Fitbit, Garmin, Wear OS, Samsung Gear/Galaxy. See <</devices/wearables#,Smartwatch and Wearables>> for supported devices.
Enable HR monitoring for devices that support direct HR over BLE (Bluetooth Low Energy)::
  _Settings -> Wearables -> Bluetooth Smart_
  This regards all other devices that have a HR sensor (such as Polar H7) and may or may not work with your device.
NOTE: Do not use this option for HR monitoring with compatible smartwatches.
Enable HR monitoring for a supported oximeter:: If you have an <</devices/oximeter#,oximeter>> connected in _Sleep -> Settings -> Wearables -> Pulse Oximeter_, heart rate will be detected by default.
Enable awake detection using heart rate data::
  _Settings -> Sleep tracking -> Awake detection -> Heart rate monitoring_

// ## Guide
//
// Heart rate levels can be gathered from smartwatches, smartbands, heart straps or from oximeters.