---
layout: default
title: Lullaby
nav_order: 2
parent: /sleep/0parent.html
tags:
- lullaby
---

:toc:

== What it does
.Plays you a lullaby when you get to bed to help you fall asleep better.

For lullabies, you can use *built-in lullabies*, your *own music*, or you can mix in *binaural beats*.

*Built-in lullabies* are composed of repetitive sounds making your brain tired and sleepy, and sudden sounds for complete and rich experience stimulating your fantasy.
Five lullabies are build in for free, five additional lullabies available after unlocking the app and many more with the https://play.google.com/store/apps/details?id=com.urbandroid.sleep.addon.lullaby[Sleep Lullaby extension pack].

For playing your *own music* (external player, Spotify, listening to audiobooks), you can use the feature "Turn off when sleeping", which is watching for you falling asleep and then will start a countdown for the set time. After that, it will gradually lower the system media volume.

*Binaural beats* mix real-time generated binaural tones into lullaby playback. Read more about https://en.wikipedia.org/wiki/Beat_(acoustics)#Binaural_beats[binaural beats].

== Where to find it
_Settings -> Lullaby_
_Left_ ≡ _menu -> Lullaby_ (only for selecting or starting lullaby, no settings)

== Options
[horizontal]
Built-in lullabies::
 * Whale diving
 * Thunderstorm
 * Mountain stream
 * White noise
 * Down in a cave
 * Fireplace
 * Ocean beach
 * Windy walk
 * Old clock
 * Chants of Tibet
Lullaby Add-ons::
 * Summer night
 * Frogs in pond
 * North wind
 * Jungle
 * Lava cake
 * Galloping horse
 * Sheep counting
 * Wind chimes
 * Om chant
 * Temple bells
 * Flute
 * Tribal drums
 * Piano
 * Cat purr
 * Steam train
 * NASA Saturn "sound"
 * Submarine
 * War march
 * Musicbox
 * Baby in belly
 * Girl singing
 * Choir
 * Slow breath
 * Spaceship
 * Brown noise
 * Pink noise
 * Forest
 * Baby Doppler
 * Heart
 * Car
 * Fireworks
 * Fan
 * Hairdryer
 * Shower
 * Shush
 * Vacuum cleaner
 * Washing machine
 * Restaurant
Turn off when sleeping:: Controls the system-wide volume level and turns it gradually down when you fall asleep.
NOTE: This feature only works when Sleep tracking is active.
 * Works with built-in lullabies and any sound player app or service.
 * You can set minimal time of playback (0-90 min).
Volume:: Controls volume of lullabies.
Sudden sounds volume:: Controls volume of sudden sounds (e.g. thunders, bubbles).
Start automatically:: Initiates lullabies automatically when tracking starts.


.Online radio section
[horizontal]
Play::
+ Online radio:: You can add you own online radio
NOTE: You need to find the URL of the online audio stream. This may or may be not the same URL as the radio web player, often the stream URL is hard to find.

Turn off WiFi after lullaby:: Turns off the WiFi signal once the volume reaches zero. For online radios and streaming services.

== Advanced Options
[horizontal]
Binaural beats:: Enables binaural beats into lullaby playback - effective only if you use the lullaby with headphones.
WARNING: We do strongly discourage users from using binaural beats if they suffer epileptic or cardiac issues!
* Delta - frequency goes down to 2 Hz
* Theta - frequency goes down to 4 Hz

Volume:: Sets a volume of binaural tones.
Binaural beats in alarm:: Configures stimulating binaural beats into alarm sound.
* Beta - frequency around 20 Hz
* Gamma - frequency around 40 Hz
Mindroid::
https://play.google.com/store/apps/details?id=com.urbandroid.mind[Mindroid]
