---
layout: default
title: Pair tracking
nav_order: 2
parent: /sleep/0parent.html
---

:toc:

== What it does
.Helps you to get a cleaner record of your sleep phases by combining the measurements from your and your partner’s phone, using any combination of sensors.

Pair tracking uses two cooperating phones (your and your partner’s) simultaneously to filter out the partner’s activity and obtain clean separate activity records.

If you do not sleep alone in your bed, tossing and turning of your partner may affect your activity measurement (hence sleep phases detection, hence smart alarm and other sleep-phase dependent features). While the interference usually isn’t too big, in certain conditions it may be enough to mix up sleep phases in your sleep record.

== Where to find it
_Settings -> Sleep tracking -> Pair tracking_

_Settings -> Sleep tracking -> Find partner_

// ## Options
// Describe all the feature's options, see other docs pages for formatting

== Guide
. Go to _Settings -> Sleep tracking_.
. First, enable pair tracking by ticking the option _Pair tracking_.
. Then you need to pair the phones, i.e. tell them that they should cooperate during sleep tracking. Tap on _Find partner_ simultaneously on the both phones. The two phones will attempt to connect to each other and form a pair.
[NOTE]
If pairing does not succeed the first time, please be patient, and try it one or two times more.
. Now the two phones know about each other. The grey cryptic string at the bottom is their shared secret, which is unique for each pair, and by which the two phones recognize each other.
//TODO obrázek

When you go to bed, you start sleep tracking as usually, and so does your partner. There is no need to start the tracking simultaneously, just use the app as you used to. During sleep tracking, the phones attempt to connect to each other and exchange their activity data, so that each phone also has a full record of the partner’s activity. From the two datasets, we are able to discount the partner’s activity and extract a clean actigraph for each sleeper. For the time periods when the partner phone is not reachable, tracking works just like it used to, calculating everything just from its local recording.

Sleep records where pair tracking was used for at least a part of the night are tagged with a new “#pair” tag and a pair TODO:(include pair icon) icon.

If you sleep alone temporarily, you may disable pair tracking, and it may save a bit of energy. The impact of pair tracking on battery consumption is however negligible.

== Troubleshooting
// To be used for automatic rendering of related FAQs
