---
layout: default
title: Sensors
nav_order: 2
parent: /sleep/0parent.html
tags:
- tracking
- sonar
---
:toc:

*Sleep as Android measures your sleep using various sensors. You can use sensors that are in your phone, or purchase additional devices and use their sensors, or use a combination.*

== Motion sensors
*Basic sleep tracking is done using a motion sensor.*

[horizontal]
Accelerometer:: Can be either in the phone or in a connected wearable. If you want to track motion using a wearable, see <</devices/wearables#,Smartwatch and Wearables>>.
Sonar:: Our invention — the sonar — uses your phone's speaker and microphone to sense movement in the near surroundings. Can be used only on the phone. Can detect breath rate in ideal conditions. <<sonar, Read more>> about Sonar.
PIR:: Passive infrared sensor is mounted on the <</devices/sleep_phaser#,Sleep Phaser>> and can detect breath rate in addition to coarse movement.

See <</sleep/sleep_tracking#how-to-track-sleep, How to track sleep>> for details on optimal setup of your sensor in the bedroom for best results.

== Sonar

Sonar brings contact-less motion tracking. No more need for a device attached to your wrist or in the bed.

You don’t need any new hardware for that – everything is already in your smartphone (check our link:https://sleep.urbandroid.org/documentation/faq/sonar-compatible-devices/[device compatibility list]): microphone, speaker and required computing power.

During tracking with sonar the phone produces ultrasonic signal (which cannot be heart by most). Even tiny movements distort the reflected signal which allows as to track them when we record them with the microphone.

On many devices Sonar tracking is so precise we are even able to track your abdominal movements and display your <</sleep/breath_rate#, Breath-rate>> in the sleep graph.

== Heart rate sensors
*Heart rate is used to better distinguish awake state.*

See <</sleep/heart_rate#,Heart rate>> docs.

== Breath rate / SpO~2~ sensors
*Breath rate detection is used to monitor healthy levels of breathing and tries to catch early signs of breathing disturbances.*

See <</sleep/breath_rate#,Breath rate>> docs.

== Light level sensors
*Ambient light sensors that are present in nearly every smartphone measure the level of ambient light in your bedroom.*

See <</sleep/light_level#,Light level detection>> docs.
