---
layout: default
title: Sleep tracking theory
nav_order: 2
parent: /sleep/0parent.html
tags:
- theory
---
:toc:

== What is sleep

Simply put, sleep is something we do when we are tired in order to get un-tired. Human bodies are constructed in a way that they need a certain period of sleep after a certain period of activity.

We expect that when we wake up, we will be feeling better than when we went to bed.

But all sleep is not the same. Whether you have a healthy sleep and feel energetic or tired during the day is a result of many factors that go together or fight against each other. In order to understand why we sleep better or worse, we need to gain deeper understanding of the factors that affect sleep, and also be able to measure sleep objectively.

Sleep as Android enables you to track *inputs* and *outcome* of your sleep (the qualities of sleep itself).

=== Sleep input factors
The state in which you go to sleep, your bedroom environment, fall asleep and awake time, what you do during the day and of course your genetics are all input factors that determine how your sleep outcome is going to turn out.

You can do something about the majority of those input factors in order to steer the outcome towards a healthy sleep.

For that, Sleep as Android gives you tools such as:

* Tags
* <</alarms/bedtime_notification#,Bedtime notifications>>
* Bedroom <</sleep/light_level#,light levels measurement>>
* Bedroom <</sleep/sleep_noise_recording#,noise measurement>>
* <</alarms/smart_wake_up#,Smart alarm>>
* <</alarms/alarm_settings#gentle_alarm,Gentle alarm volume increase>> & <</devices/smart_light#sunrise_alarm_guide,gentle alarm light increase / sunrise alarm>>

=== Sleep outcome
Sleep outcome is the actual shape of your sleep - the way it turns out. There are several ways to establish the quality of the sleep outcome, which together form a picture of your healthy your sleep is.

So when we want to know how well you sleep, we look at:

* Sleep phases - especially the ratio of deep sleep versus light sleep
* Duration of your sleep
* Efficiency, ie. how long you're actually sleeping vs. being in bed
* Detected snoring duration
* Your subjective quality rating

Those six dimensions together form your <</sleep/sleepscore#,sleep score>>.

== How is sleep tracked

Sleep scientists track sleep using two main methods:

- PSG (polysomnography)
- actigraphy

=== PSG, polysomnography
PSG is the first method used to measure sleep. If you go to a sleep lab, you will with 99% certainty undergo PSG.

This is the 'heavyweight' method - the patient is usually wearing a lots of sensors:

- EEG (to measure brain activity),
- EOG (to measure eye muscle movements),
- actigraphs (to measure overall movement),
- EKG (to measure heart activity),
- Pulse oximeter (to measure blood oxygenation level),
- EMG (to measure other muscle movements),
- and possibly other sensors.

PSG is regarded as a golden standard in sleep science as it measures the most sleep dimensions.

PSG distinguishes REM sleep and non-REM sleep. Non-REM is further divided into N1, N2, N3 phases.

The biggest criticism of PSG is that it is too invasive - the patient is not in his home environment and is entangled in a lots of wires and other electronics that prevent him from sleeping naturally. This complicates diagnostics.

=== Actigraphy
Actigraphy is a sleep tracking method that's been on the rise first with wrist-worn actigraphs used by clinical sleep scientists, and later with the introduction of smartphones on the market as a comfortable solution for sleep tracking at home.



=== PSG compared to actigraphy

//-- PsG phases vs. actigraphic phases, what is deep sleep,light sleep

//== Why track your sleep
