---
layout: default
title: Smart wakeup
nav_order: 2
parent: /sleep/0parent.html
tags:
- tracking
- alarm
---

:toc:

== What it does
*Looks for the best moment to wake you up for a great morning.*

Waking up in light sleep feels natural - like on a weekend, without any alarm.
In contrast, deep sleep wake up (which is common with ordinary alarm clocks) leads to an unpleasant experience accompanied with feeling of tiredness, sleepiness, disorientation.

With smart wake up, you set up a time window (also called Smart wake up period), in which you’d like to be woken up once it is the right moment.

[EXAMPLE]
Alarm time: 8:00
Smart period: 30 minutes (default)
Sleep as Android will wake you between 7:30-8:00, once you are in light sleep for some time. The scheduled alarm time (8:00) is considered as the last possible wake up time.

== Where to find it
_Settings -> Sleep tracking -> Smart wake up_

== Options
[horizontal]
Smart period:: Set the smart period - time window before alarm to be awoken in.
* Disabled - alarm goes off exactly at alarm time
* Power nap - special type of smart period which wakes you after the alarm time, see <</alarms/power_nap#,Power nap>>
* 5 minutes - 2 hour - alarm goes of during the selected period prior to alarm time
Nap smart period:: sets a smart period for naps with tracking and naps from shortcuts
* Disabled - alarm goes off at alarm nap time
* Power nap - See <</alarms/power_nap#,Power nap>>
* 5 minutes - 2 hour - alarm goes of during the selected period prior to alarm time

== Advanced options
[horizontal]
[[sensitivity]]
Movement sensitivity:: Adjust sensitivity of smart alarm. With less sensitivity, you need more noticeable movement to trigger alarm.
Not before ideal sleep:: Does not allow the alarm to ring before reaching either ideal sleep duration or alarm time.
WARNING: In some cases this option can render Smart wake up ineffective. It can lead to ignoring the smart period for the sake of reaching ideal sleep duration.
