---
layout: default
title: Statistics
nav_order: 2
parent: /sleep/0parent.html
---

:toc:

## What it does

Statistics show the most important dimensions (Duration, Deep sleep, Snoring) of your <</sleep/sleepscore.html#,Sleep score>> aggregated by days or optionally by <</sleep/tags#,Tags>>.

## Where to find it

*Left ☰ menu -> Stats* or from the <</ux/homescreen#sleepscore,Sleep Score>> dashboard card.

## What you see

Each row in the Stats screen shows day-aggregated Duration, Deep sleep and Snoring.
The aggregate is calculated from all tracked sleeps - let's call them <</sleep/sleep_graph#,Graphs>> in the further text - which belong to the same day.

The list of days is based on the period selection in top right (Week, 14 days, Month...) but is limited to last 30 days.

By default Graphs belong to the same day if their end time belongs to the same day. But this can be modified in _Setting -> Sleep -> Stats -> More -> Sleep day cutoff_ in case of specific sleeping schedules.

Optionally aggregates by Tags can be expanded by tapping on _Show X Tags_. This will tell you how does your Duration, Deep sleep and Snoring differ when a certain tag is used to your Sleep score for all nights. The aggregates are calculated fro the selected period which can be changed in top right.

A special row in the Tags section shows your country and aggregated Duration, Deep sleep and Snoring for your fellow citizens.
