---
layout: default
title: Tags
nav_order: 2
parent: /sleep/0parent.html
---
:toc:

== What it does
*Tags allow you to find out how various lifestyle events affect your sleep.*

== Where to find it
Tags can be added:

- while sleep tracking, by tapping the icon:ic_pencil[] button
- in the rating screen, after you finish sleep tracking
- in any sleep record, by tapping the big icon:ic_pencil[] button

== Guide

=== Adding tags
You can add tags to any sleep record by including it in the comment section of the record. Any word can become a tag if you prefix it with #. Emoji also count as tags. See also <</sleep/graph_edit#,editing tags>>.

There are also predefined icon tags, and a handful of automatically added tags.

|===
a|Automatically added tags a|Icon tags

a|icon:ic_action_newmoon[]#newmoon
icon:ic_action_fullmoon[] #fullmoon
icon:ic_action_rain[] #rain
icon:ic_action_storm[] #storm
icon:ic_cloud[] #cloudy
icon:ic_action_cold[] #cold
icon:ic_action_hot[] #hot
icon:ic_action_watch[] #watch
icon:ic_action_geo1[] #geo01
icon:ic_action_geo2[] #geo02
icon:ic_action_geo3[] #geo03
icon:ic_action_geo0[] #geo00
icon:ic_action_home[] #home
icon:ic_cloud_upload[] #cloud
icon:ic_action_lullaby[] #lullaby
icon:ic_sonar[] #sonar
icon:ic_sleep_phaser[] #phaser
icon:ic_pair[] #pair
icon:ic_automagic[] #auto (automatic tracking)
a|icon:ic_action_food[] #food
icon:ic_walk[] #sport
icon:ic_martini[] #alcohol
icon:ic_action_stress[] #stress
icon:ic_action_lullaby[] #caffeine
icon:ic_action_love[] #love
icon:ic_action_med[] #med
icon:ic_action_dream[] #dream
icon:ic_action_talk[] #talk
icon:ic_action_noise[] #snore
icon:ic_action_laugh[] #laugh
icon:ic_action_sick[] #sick
icon:ic_action_work[] #work
icon:ic_action_cpap[] #cpap
icon:ic_action_baby[] #baby
icon:ic_action_mic[] #note
icon:ic_dream_good[] #gooddream
icon:ic_dream_bad[] #baddream
icon:ic_action_menses[]#menses

|===

=== Analyzing tags
Tags divide your sleep history so you can compare nights with a given tag to nights without that tag. See <</sleep/charts#tags, Charts>>.


This can be done in the Stats tab (in the image below). There is a collapsible Tags section which shows average sleep measures so that you can easily compare your overall average measures (sleep length, deep sleep, snoring…) with your tagged results. If you observe for example significant drop in deep sleep % after using caffeine you may consider to reduce caffeine consumption (especially before sleep) in order to improve your deep sleep %.

Coloring
We use green for surplus and red for deficit on sleep length.
For deep sleep % we calculate the average value:
if +-15% from the average the coloring is green
for any unusual values out of the average we use red.
Values above the average may mean some error of measurement – for example the phone was not close enough to the body. Values under average may indicate too much light sleep due to various factors such as stress, alcohol consumption, loud environment etc…

Another insight into tagging is provided in Charts. There you can see effects of life style events in various bar charts. For example the effect on snoring:

Custom tags

Rating
Rating is another quality criterion which adds subjective evaluation of our sleep. Similarly to deep sleep % we can show what sleep measures lead to your higher satisfaction with your sleep. Rating is added as 0-5 stars with 5 starts being the best rating. Sleep can be rated on the same dialog which is also used for adding tags.
Location tagging – geo tags
We use network-based location to implement some of the cool location based features such as wake up with sunrise, location tagging, and morning weather.
In the geotagging feature, we calculate the 4 most frequent places from your sleep tracking history, so the most-frequent place is considered “home”, the second one is “geo1”, then “geo2” and finally “geo3”.
The location we use is coarse and we store it even coarser, +/- 5 km. In effect, we identify your location as a square and then match those squares to set up the location tags.
You can completely turn off location storing in Settings > Miscellaneous.


The only requirement is using the hash mark notation at the start, followed by any number of alphanumeric character (For example #headache or #travel).

Frequency tracking
It is also possible to track frequency of your events. For example #caffeeine_3x – meaning 3 coffees, #alcohol_2x – 2 shots, #sport_3x – 3 hours of sport. This allows to describe your lifestyle events more precisely. Support for automated analysis of the frequency information is not yet included in the app, but it is planned in coming versions.
You can add frequencies easily but pressing the tag button multiple times. To delete a tag on the other hand — long press the tag icon.

You can add tags in the morning dialog after you finish sleep tracking, or from the tracking screen any time during the tracking.
