---
layout: default
title: Tags
nav_order: 2
parent: /sleep/0parent.html
---
:toc:

== What it does
*Tags allow you to find out how various lifestyle events affect your sleep.*

== Where to find it
Tags can be added:

- while sleep tracking, by tapping the icon:ic_pencil[] button
- in the rating screen, after you finish sleep tracking
- in any sleep record, by tapping the big icon:ic_pencil[] button

== Guide

=== Adding tags
You can add tags to any sleep record by including it in the comment section of the record. Any word can become a tag if you prefix it with #. Emoji also count as tags. See also <</sleep/graph_edit#,editing tags>>.

There are also predefined icon tags, and a handful of automatically added tags.

|===
a|Automatically added tags a|Icon tags

a|icon:ic_action_newmoon[]#newmoon
icon:ic_action_fullmoon[] #fullmoon
icon:ic_action_rain[] #rain
icon:ic_action_storm[] #storm
icon:ic_cloud[] #cloudy
icon:ic_action_cold[] #cold
icon:ic_action_hot[] #hot
icon:ic_action_watch[] #watch
icon:ic_action_geo1[] #geo01
icon:ic_action_geo2[] #geo02
icon:ic_action_geo3[] #geo03
icon:ic_action_geo0[] #geo00
icon:ic_action_home[] #home
icon:ic_cloud_upload[] #cloud
icon:ic_action_lullaby[] #lullaby
icon:ic_sonar[] #sonar
icon:ic_sleep_phaser[] #phaser
icon:ic_pair[] #pair
icon:ic_automagic[] #auto (automatic tracking)
a|icon:ic_action_food[] #food
icon:ic_walk[] #sport
icon:ic_martini[] #alcohol
icon:ic_action_stress[] #stress
icon:ic_action_lullaby[] #caffeine
icon:ic_action_love[] #love
icon:ic_action_med[] #med
icon:ic_action_dream[] #dream
icon:ic_action_talk[] #talk
icon:ic_action_noise[] #snore
icon:ic_action_laugh[] #laugh
icon:ic_action_sick[] #sick
icon:ic_action_work[] #work
icon:ic_action_cpap[] #cpap
icon:ic_action_baby[] #baby
icon:ic_action_mic[] #note
icon:ic_dream_good[] #gooddream
icon:ic_dream_bad[] #baddream
icon:ic_action_menses[]#menses

|===

=== Analyzing tags
Tags divide your sleep history so you can compare nights with a given tag to nights without that tag. See <</sleep/charts#tags, Charts>>.
