---
layout: default
title: Tags
nav_order: 2
parent: /sleep/0parent.html
tags:
- graph
- tag
---
:toc:

== What it does
*Tags allow you to find out how various lifestyle events affect your sleep.*

== Where to find it
Tags can be added:

- while sleep tracking, by tapping the icon:ic_pencil[] button
- in the rating screen, after you finish sleep tracking
- in any sleep record, by tapping the big icon:ic_pencil[] button

== Guide

=== Adding tags
You can add tags to any sleep record by including it in the comment section of the record. Any word can become a tag if you prefix it with \#. Emoji also count as tags. See also <</sleep/graph_edit#,editing tags>>.

There are also predefined icon tags, and a handful of automatically added tags.
The tags are arranged in the order based on the frequency of use.

==== Icon tags
You can choose from the list of pre-defined tags with icons, which include the most common lifestyle events which have some relevance to sleep.

|===
a|Icon tags

a|icon:ic_action_food[] #food
icon:ic_walk[] #sport
icon:ic_martini[] #alcohol
icon:ic_action_stress[] #stress
icon:ic_action_lullaby[] #caffeine
icon:ic_action_love[] #love
icon:ic_action_med[] #med
icon:ic_action_dream[] #dream
icon:ic_action_talk[] #talk
icon:ic_action_noise[] #snore
icon:ic_action_laugh[] #laugh
icon:ic_action_sick[] #sick
icon:ic_action_work[] #work
icon:ic_action_cpap[] #cpap
icon:ic_action_baby[] #baby
icon:ic_action_mic[] #note
icon:ic_dream_good[] #gooddream
icon:ic_dream_bad[] #baddream
icon:ic_action_menses[]#menses
|===


==== Automatically added tags
Some tags are calculated and added to your sleep record automatically. You can turn this feature off in _Settings -> Sleep -> More -> Stats -> Automatic tagging_.

|===
a|Automatically added tags

a|icon:ic_action_newmoon[] \#newmoon (that night was new moon)
icon:ic_action_fullmoon[] #fullmoon (that night was full moon)
icon:ic_action_rain[] #rain (rainy weather report)
icon:ic_action_storm[] #storm (stormy weather report)
icon:ic_cloud[] #cloudy (cloudy weather report)
icon:ic_action_cold[] #cold (temperature below 5°C)
icon:ic_action_hot[] #hot (temperature over 28°C)
icon:ic_action_watch[] #watch (tracking with <<devices/wearables#,wearable>>)
icon:ic_action_home[] \#home (tracking at home (most tracked location))
icon:ic_action_geo0[] #geo00 (tracking at 2nd most tracked location)
icon:ic_action_geo1[] #geo01 (tracking at 3rd most tracked location)
icon:ic_action_geo2[] #geo02 (tracking at 4th most tracked location)
icon:ic_action_geo3[] #geo03 (tracking at 5th most tracked location)
icon:ic_cloud_upload[] #cloud (this sleep record originates from a cloud service)
icon:ic_action_lullaby[] #lullaby (tracking with <</sleep/lullaby#,lullaby>> running)
icon:ic_sonar[] \#sonar (tracking with <</sleep/sensors#sonar,Sonar>>)
icon:ic_sleep_phaser[] #phaser (tracking with <</devices/sleep_phaser#,Sleep Phaser>>)
icon:ic_pair[] \#pair (<</sleep/pair_tracking#,pair tracking>> was active)
icon:ic_automagic[] \#auto (<</sleep/automatic_sleep_tracking#,automatic tracking>>)
icon:ic_lightbulb_off[] \#dark (less than 30 lux for at least 90% of the night, see <</sleep/light_level#, Light level tracking>>)
icon:ic_lightbulb[] \#light (more than 60 lux for at least 33% of the night, see <</sleep/light_level#, Light level tracking>>)
|===

===== Location tags

We calculate the 4 most frequent places in the past year of your data history. One year should be sufficient so that you can e.g. watch your sleep at your holiday home where you go regularly in the summer.

Should you move, your new home will gradually become #geo3 -> #geo2 -> #geo1 ->    #home after some time as it becomes dominant in your data.

You can also reset your home location any time using _Settings -> Privacy -> Reset home location_.

NOTE: <</general/permissions#location,Location permission>> needs to be granted.

The location we use is coarse and we store it even coarser, +/- 5 km. In effect, we identify your location as a square and then match those squares to set up the location tags.
You can completely turn off location storing in _Settings -> Privacy -> Don't store sleep location_.

===== Moon phases

3 days around full moon or new moon graphs will get a \#fullmoon or #newmoon tags. You can see how the moon cycle affects your sleep in <</sleep/charts#tags, Charts>> or <</sleep/statistics#, Stats>>.

===== Sensor

If you use a wearable or sonar, a #watch or #sonar tag will appear on your graph.

===== Automatic sleep tracking

If sleep tracking was started automatically for your (you did not hit the _icon:ic_action_track[] Sleep tracking_ button) an #auto tag will be added.

You can see more on this feature <</sleep/automatic_sleep_tracking#, here>>.

===== Pair tracking

If <</sleep/pair_tracking#, pair tracking>> was used #pair tag will be added.

==== Custom tags
You can create your own personal tag, the only requirement is using the hash mark notation at the start, followed by any number of alphanumeric character (For example #headache or #travel).

==== Frequency tracking
It is also possible to track frequency of your events. For example #caffeine_3x – meaning 3 coffees, #alcohol_2x – 2 shots, #sport_3x – 3 hours of sport. This allows to describe your lifestyle events more precisely.

NOTE: Support for automated analysis of the frequency information is not yet included in the app, but it is planned in coming versions.

You can add frequencies easily but pressing the tag button multiple times. To delete a tag on the other hand — long press the tag icon.

=== Editing tags

Your personal tags can be edited, if needed. The tags will be changed on all graphs and also for the statistics.

video::7edhMVA3t1g[youtube]

NOTE: You can edit only text tags, emoji tags cannot be altered at this moment.

==== Renaming tags
1. Open the list of graphs from the _Left_ ☰ _menu -> Graphs_.
2. Long press on the graph and select _Rename tag_.
3. To the first field, type the old name of your tag.
4. To the second field, type the new name of your tag.
5. Confirm with OK button.
6. Confirm the 'Are you sure?' dialogue.

==== Deleting tags

1. Open the list of graphs from the _Left_ ☰ _menu -> Graphs_.
2. Long press on the graph and select _Rename tag_.
3. To the first field, type the old name of your tag.
4. Keep the second field empty.
5. Confirm with OK button.
6. Confirm the 'Are you sure?' dialogue.


=== Analyzing tags
Tags divide your sleep history so you can compare nights with a given tag to nights without that tag. See <</sleep/charts#tags, Charts>>.
You can evaluate the influence of tags in <</sleep/charts#tags, Charts>> and in <</sleep/statistics#tags, Statistics>>

In <</sleep/statistics#,Stats>>, there is a collapsible Tags section which shows average sleep measures so that you can easily compare your overall average measures (sleep length, deep sleep, snoring…) with your tagged results. If you observe e.g. a significant drop in deep sleep % after drinking coffee, you may consider to reduce caffeine consumption (especially before sleep) in order to improve your deep sleep %.
