---
layout: default
title: Widgets
nav_order: 2
parent: /sleep/sleep_advanced.html
---

:toc:

== What it does
.You can choose different widgets for your phone's screen, each with different function.

== Where to find it
Long press on an empty space on your phone screen -> Widgets -> scroll down until you see Sleep.

== Options
//TODO all images
[horizontal]
Tracking widget:: Starts a tracking and reminds you when to go to bed with colors.Two hours before the bedtime, shows the countdown. When you reach bedtime, the widget turns red as a warning that you should go to sleep ASAP. Tapping on tracking widgets initiates sleep tracking.
Alarm widget:: Shows the time of the next alarm. Its color reflects the day of the week of the next alarm from Monday – Red, to Friday and Weekend – Green, to reflect the usually work week day sentiments :). Clicking on it brings you to the Sleep application.
Droid widget (icon):: Changes appearance depending on time, date, day of the week and other factors. Find out all the droid faces! Tapping on it brings you to the Sleep application
Hypnogram widget:: Shows your last hypnogram, opens the last graph.

.Shortcut widgets
When long pressing the Sleep icon, you can create new widgets from your shortcuts on shortcut card on <</ux/homescreen#,Dashboard>>.
[horizontal]
Add alarm:: Creates a widget for quick access to the dialogue for creating a new alarm.
Nap X min:: Creates a nap from your last used nap.
Ideal sleep length:: Creates a widget to start tracking to reach your ideal daily sleep income set in _Settings_ (accounts for sleep tracking delay and smart period, to ensure you really reach the needed sleep income).
Sleep tracking:: Starts tracking.

== Troubleshooting
// To be used for automatic rendering of related FAQs
