---
layout: default
title: Get started with Sleep as Android app
nav_order: 202
//parent: /general/general_info.html
tags:
- purchase
---
:toc:

== Why do I need a sleep tracking app?

Sleep is essential for maintaining optimal health, both physical and mental.
Consistent sleep monitoring can help you understand the influence of various factors and your lifestyle on your sleep quality, habits and thus your overall health and longevity.
Important part of this experience is our smart wake up which makes your morning more pleasant. The app triggers the alarm during light sleep when it feels natural - just like waking up without an alarm at all.


== What exactly can the app measure?

The app is collecting data about your movement, your body vital signs (HR, HRV, SpO2, breath rate), about the environment (light and sound level), and about your lifestyle (from the added tags, like #coffee, #sport...), to create a complex image of your sleep.
The movement data from the sensor are evaluated by https://sleep.urbandroid.org/how-do-we-measure-your-dreams/[unique algorithms] to estimate your sleep phases. This method used is called *actigraphy* (you can read more in the <<sleep/sleep_tracking_theory, Sleep tracking theory chapter>>). After each night, you will get a <<sleep/how_to_read_sleep_graph, sleep graph>>, and after the app collects enough data for long-term statistic, you can explore your sleep quality patterns in your <<sleep/statistics, Stats and Trends>>.


== Why Sleep Score with several values and not Sleep Quality?

There isn't a single number which would tell you whether your sleep is good or bad. There isn't a 85% sleep quality figure which some may try to convince you of. Instead, sleep has several parameters and you are trying to keep all those in favourable limits.
This is what we call the <</sleep/sleepscore,Sleep score>> where we evaluate your duration, regularity, depth of sleep, snoring, heart rate variability or oxygenation (depending on the device you use).
From a single night you can check if you slept long enough and how much you snored, but the data start to be interesting with more nights tracked where you start seeing trends - am I improving my regularity? Is my sleep deficit getting down? etc..
If you see you are consistently behind some target for any of your dimensions, you can setup <</sleep/goals,goals>>. For instance you are sleeping just 6:00 on average which is quite bad for an adult, so you can setup a goal to increase your sleep duration to at least 6:30 and the app will guide you gradually to achieve that goal...
The app will point out some notable trends and also suggest some changes in the <<sleep/advice,Advice section>>.


== Quick video tour in the app



== Quick video guide for first sleep tracking with an alarm



== Quick video guide for creating a repeating work-day alarm


== Quick video guide for connecting a wearable