---
layout: default
title: Awake detection
nav_order: 2
parent: /docs/sleep_basic/sleep_tracking.html
---

:toc:

== What it does
.Estimates your awake periods using either light detection, heart rate detection, detection of using a phone, or pause feature.

Since actigraphy is not powerful enough to distinguish you being awake in the bed and not moving from being out of bed for toilet, sleep uses several tricks to estimate your awakes periods - like measuring the light, phone position, and heart rate peaks.

== Where to find it
_Settings -> Sleep tracking -> Awake detection_

== Options

[horizontal]

Movement intensity:: Estimated from awake like events based on acceleration threshold
Heart rate monitoring::
Any HR peak significantly higher than the average in the last 5 minutes is marked as awake period.
. Your heart beats up to 10 BPM slower during sleep, than when awake.
. The app supports most Bluetooth heart rate devices via BLE, and various smartwatches. Please refer to <</docs/connected_devices#,Wearable>> for more details.
Light:: The ambient light sensor measures the level of ambient light in your bedroom
 * If there is disturbing light (more than 30 lux) after sunset, we consider it as an Awake period.
 * The #dark (TODO ikona) tag is added when you have less than 30 lux for at least 90% of the night.
 * The #light (TODO ikona) tag is added when you have more than 60 lux for at least 33% of the night.
Talk:: The talk-like sounds (talking, baby cry or cough) indicates awake.
 * 45 minutes after beginning of tracking and 1 hour before alarm for automatic tracking.
 * At least 4 talk-like events in last minute for manual tracking start.
Snooze:: Turns any snooze or pause result into awake.
Awake when using phone:: Adds awake automatically when the phone is held in unusual position or used.

.Pause tracking

[horizontal]
Delayed sleep tracking:: Configures automatic pause time at sleep tracking start if you know your typical fall asleep sequence.
Flip to pause:: Allows you to add 5 min pause by flipping the phone.

== Pause

Use the sleep tracking pause feature whenever you are tracking but not sleeping.

[horizontal]
Pause button:: Available from sleep tracking screen.
* Displays the time left,
* Finished without your further interaction,
* You may add +5 minutes anytime.
Volume / camera buttons:: Adds 5 minutes every time your press the volume of camera buttons
* Needs to be enabled in _Settings -> Sleep tracking -> Volume and camera button effect_
* When screen off - press the power button and than one of the volume buttons or camera button.

NOTE: You can also edit your sleep graph ex-post in order to correct your wake up or before fall asleep periods. See Guide for detailed instructions.


== How to…

[horizontal]

Mark any period as awake::
. Open the graph you wish to edit from _Left_ ☰ _menu -> Graphs ->_ open the graph.
. Select any portion of the graph by taping on the graph directly.
. Adjust the selection once the selected portion gets zoomed - either move the selection handles or correct the timings in the upper left corner (TODO obrázek).
. When the proper time period is selected, tap on the (TODO obrázek) scissors icon.
* You can revert up to 5 changes from the ⋮ _menu -> Undo_, or immediately a banned with _Undo_ button is displayed each time you edit the graph.
Delete false-positive awakes::
. Open ⋮ _menu -> Delete awake_.
* Deletes all awakes from the graph.


== Troubleshooting
