---
layout: default
title: Backup
nav_order: 2
tags:
- backup
---
:toc:

== What it does
*Make sure to never lose your data with either local manual backup or automated cloud backup.*

== Where to find it
- _Left_ ≡ _menu -> Backup_
- _Settings -> Services -> Cloud backup_

== Options
._Left ☰ menu -> Backup_
[horizontal]
Export data:: TODO: Exports all your sleep records to a CSV file located on your phone at _/sdcard/sleep-data/sleep-export.csv_. Use for  <<local_backup,local backup>> or for your <<csv_export, own analysis>> of sleep tracking data.
Upload to Cloud:: Starts synchronization set in _Settings -> Services -> Cloud backup_ and uploads data from phone to cloud.
Import data:: Starts import of data from /sdcard/sleep-data/sleep-export.csv (local backup).
NOTE: If you already have existing sleep records in Sleep, import will not overwrite them. It will just import new records that are present in the import file.
Download from Cloud:: Starts synchronization set in _Settings -> Services -> Cloud backup_ and downloads data from cloud to app.

._Settings -> Privacy -> [Backup]_
[horizontal]
SleepCloud:: See <<sleepcloud_backup,SleepCloud backup>>
Cloud backup:: Main switch for cloud backup. If disabled, no cloud backup will take place.
Local storage backup:: If disabled, Sleep will not be doing daily <<local_backup>>.
Restore settings:: Restore app's settings from locally saved `prefs.xml` file. See <<local_backup>> for details.

// Google Drive:: See <<google_drive,Google Drive>>
// Dropbox:: See <<dropbox,Dropbox>>

== Guide

### Local backup
[[local_backup]]
Backs up: *Sleep records, Settings, Noise recordings, Noise recordings metadata*

Your data are being backed up on a daily basis to `/sdcard/sleep-data/` folder on your phone. You can also start local backup manually using _Left_ ☰ _menu -> Backup -> Export data_.

What is backed up in this folder:
[horizontal]
/rec folder:: Contains all your recorded noise files.
noise.json:: Noise metadata
prefs.xml:: Settings
sleep-export.csv:: Latest sleep data
sleep-export.backup.csv:: Sleep data from the previous backup

To migrate your data to another phone:

. Move the `/sdcard/sleep-data/` folder to your new phone, same location - `/sdcard/sleep-data/`.
. Import the data with _Left_ ☰ _menu -> Backup -> Import data_ immediately.
+
NOTE: If you don't import immediately, the app will replace your `sleep-export.csv` file after the next sleep record is created. The old `sleep-export.csv` file will be renamed to `sleep-export.backup.csv`. See <</faqs/backup_data_not_imported_immediately,solution>>.
[[csv_export]]
+


You can open the CSV file on your computer (e.g. in Excel) for your own analysis of the sleep tracking data. The structure of the CSV file is <</docs/developers/csv#,documented here>>.

### Backup to SleepCloud (recommended)
[[sleepcloud_backup]]
Backs up: *Sleep records, Settings, Noise recordings metadata*
Does not back up: *Noise recordings*

Recommended backup service. It stores data in our own cloud designed for Sleep as Android. It has several unique features not present in other backup methods.

#### Prerequisites
- You need https://play.google.com/store/apps/details?id=com.urbandroid.sleep.addon.port[SleepCloud Backup add-on] installed on your phone.

- In order to use SleepCloud, you need to have a valid Google account and grant us a permission to use this account when connecting to the cloud.

#### Setting up
. Go to _Sleep -> Settings -> Privacy -> SleepCloud_ and connect _SleepCloud_.

#### Features
* Free SleepCloud service automatically initiates back up once a week.
* The paid PRO version automatically initiates backup when some relevant change happens (a new graph was added, an old graph was edited, etc.). You can force backup using _Left_ ≡ _menu -> Backup -> Upload to Cloud_

* You can view and modify your data online, by visiting https://sleep-cloud.appspot.com/SleepCloud.html[SleepCloud].
* Unlike other services, it does a full synchronization of records including deleting/updating of existing records. This makes it the most suitable service to synchronize data among multiple devices.
* It uses optimized communication protocols, so it consumes least data of all services.
* Synchronizes all of your settings (including active alarms), so if you get a new phone, just install SleepCloud backup and all your settings will be downloaded along with the records. It works in an inobtrusive way, so if you’ve changed any of the settings on the new phone already, they won’t get overwritten.

### Backup to Dropbox or Google Drive
[[dropbox]][[google_drive]]
Backs up: *Sleep records*
Does not back up: *Settings, Noise recordings metadata, Noise recordings*

To automatically backup your data to Dropbox or Google Drive:
. Install https://play.google.com/store/apps/details?id=com.urbandroid.sleep.addon.port[SleepCloud Backup add-on].
. Go to _Sleep -> Settings -> Services -> Cloud backup_ and connect either _Google Drive_ or _Dropbox_.

* Free SleepCloud service automatically initiates back up once a week.
* The paid PRO version automatically initiates backup when some relevant change happens (a new graph was added, an old graph was edited, etc.). You can force backup using _Left_ ≡ _menu -> Backup -> Upload to Cloud_.

### Backup using Google provided backup cloud
[[google_backup]]
Backs up: *Sleep records, Settings, Noise recordings metadata*
Does not back up: *Noise recordings*

Most Android phones support Google provided backup. This is an optional feature and it must be explicitly enabled by the user.

NOTE: We recommend using other methods, preferably <<sleepcloud_backup,SleepCloud>>, to backup your sleep records, as we have no direct control over initiation of Google backup so it may not work in all cases. This method is NOT meant to be used for synchronization of data or settings across phones.

. Enable Backup to Google Drive in  _System Settings -> System -> Backup_ (might be hidden under Advanced options) -> _Back up to Google Drive_ - our application will backup your graphs and your alarms to a Google cloud (automatically in background; you do not need to do anything).

. Enable _Automatic restore_ option in _System Settings -> System -> Backup_ (might be hidden under Advanced options) -> _App data_ - when you install a new installation of Sleep as Android on a phone where the Automatic restore option is enabled, all data will be automatically imported. You’ll get your sleep records and your alarm settings restored.

. In case you have developer tools available, you can force Google backup and restore to get reliable results. To force the backup, you can run “adb backup -f sleep-backup.bk com.urbandroid.sleep” when the old device is connected and to upload the backup to a new device run “adb restore sleep-backup.bk”.