---
layout: default
title: Lullaby
nav_order: 2
// parent: /docs/sleep_basic/sleep_tracking.html
---

:toc:

## What it does
.Plays you a lullaby while sleep tracking to help you fall asleep better.

*Built-in lullabies* are composed of repetitive sounds making your brain tired and sleepy, and sudden sounds for complete and rich experience stimulating your fantasy.
 &gt; 5 lullabies are build in for free, 5 additional lullabies available after unlocking the app and many more with the https://play.google.com/store/apps/details?id=com.urbandroid.sleep.addon.lullaby[Sleep Lullaby extension pack]

You can also use any external sound player for playing your *own music* as a lullaby, or you can try *binaural beats*.

== Where to find it
_Settings -> Lullaby_
_Left_ ≡ _menu -> Lullaby_ (only for selecting or starting lullaby)

== Options
[horizontal]
// TODO

Play:: selection of built-in lullabies
 * Whale diving
 * Thunderstorm
 * Mountain stream
 * White noise
 * Down in a cave
 * Fireplace
 * Ocean beach
 * Windy walk
 * Old clock
 * Chants of Tibet
* *Lullaby Add-ons* - unlock additional lullaby sounds
 * Summer night
 * Frogs in pond
 * North wind
 * Jungle
 * Lava cake
 * Galloping horse
 * Sheep counting
 * Wind chimes
 * Om chant
 * Temple bells
 * flute
 * TRibal drums
 * Piano
 * Cat purr
 * Steam train
 * NASA Saturn "sound"
 * Submarine
 * War march
 * Musicbox
 * Baby in belly
 * Girl singing
 * Choir
 * Slow breath
 * Spaceship
 * Brown noise
 * Pink noise
 * Forest
 * Baby Doppler
 * Heart
 * Car
 * Fireworks
 * Fan
 * Hairdryer
 * Shower
 * Shush
 * Vacuum cleaner
 * Washing machine
 * Restaurant
 * Stop
Turn off when sleeping:: controls the system-wide volume level and turns it gradually down when you fall asleep

 * Works with built-in lullabies and any sound player app
 * You can set minimal time of playback (0-90 min)
NOTE: This feature only works when Sleep tracking is active

Volume:: controls overall volume of lullabies
* *Sudden sounds volume* - controls volume of sudden sounds (e.g. thunders, bubbles)
* *Start automatically* - initiates lullabies automatically when tracking starts

—
[horizontal]
Online radio section
Play::
+ Online radio::
Turn off WiFi after lullaby::

—
*Binaural beats (advanced option)*
 &gt; effective only if you use the lullaby with headphones
 &gt; CAUTION: We do strongly discourage users from using binaural beats if they suffer epileptic or cardiac issues!
* *Binaural beats* - mixes real-time generated binaural tones into lullaby playback, read more (<span style="color:red">TODO odkaz</span>)

* delta - frequency goes down to 2 Hz
* theta - frequency goes down to 4 Hz
* *Binaural beats in alarm* - configures stimulating binaural beats into alarm sounds
* beta - frequency around 20 Hz
* gamma - frequency around 40 Hz
* *Mindroid* -
https://play.google.com/store/apps/details?id=com.urbandroid.mind[Mindroid]

___

== How to
// TODO
[horizontal]
Use podcast / audiobook::

== Troubleshooting
// TODO
[horizontal]
Volume jumps to max when tracking::
Lullaby got recorded::
Sonar audible in lullabies::