---
layout: default
title: Lullaby
nav_order: 2
// parent: /docs/sleep_basic/sleep_tracking.html
---

:toc:

== What it does
.Plays you a lullaby while sleep tracking to help you fall asleep better.


For lullabies, you can use *built-in lullabies*, your *own music*, or you can try *binaural beats*.

*Built-in lullabies* are composed of repetitive sounds making your brain tired and sleepy, and sudden sounds for complete and rich experience stimulating your fantasy.
Five lullabies are build in for free, five additional lullabies available after unlocking the app and many more with the https://play.google.com/store/apps/details?id=com.urbandroid.sleep.addon.lullaby[Sleep Lullaby extension pack].

For playing your *own music* (external player, Spotify, listening audiobooks), you can use the feature "Turn off when sleeping", which is watching for you falling asleep and then will start a countdown for the set time. After that, it will gradually lower the system media volume.

*Binaural beats* mix real-time generated binaural tones into lullaby playback. Read more about https://en.wikipedia.org/wiki/Beat_(acoustics)[binaural beats].
== Where to find it
_Settings -> Lullaby_
_Left_ ≡ _menu -> Lullaby_ (only for selecting or starting lullaby)

== Options
[horizontal]
Built-in lullabies::
 * Whale diving
 * Thunderstorm
 * Mountain stream
 * White noise
 * Down in a cave
 * Fireplace
 * Ocean beach
 * Windy walk
 * Old clock
 * Chants of Tibet
Lullaby Add-ons::
 * Summer night
 * Frogs in pond
 * North wind
 * Jungle
 * Lava cake
 * Galloping horse
 * Sheep counting
 * Wind chimes
 * Om chant
 * Temple bells
 * Flute
 * Tribal drums
 * Piano
 * Cat purr
 * Steam train
 * NASA Saturn "sound"
 * Submarine
 * War march
 * Musicbox
 * Baby in belly
 * Girl singing
 * Choir
 * Slow breath
 * Spaceship
 * Brown noise
 * Pink noise
 * Forest
 * Baby Doppler
 * Heart
 * Car
 * Fireworks
 * Fan
 * Hairdryer
 * Shower
 * Shush
 * Vacuum cleaner
 * Washing machine
 * Restaurant
Turn off when sleeping:: Controls the system-wide volume level and turns it gradually down when you fall asleep.
NOTE: This feature only works when Sleep tracking is active.
 * Works with built-in lullabies and any sound player app or service.
 * You can set minimal time of playback (0-90 min).
Volume:: Controls volume of lullabies.
Sudden sounds volume:: Controls volume of sudden sounds (e.g. thunders, bubbles).
Start automatically:: Initiates lullabies automatically when tracking starts.


.Online radio section
[horizontal]
Play::
+ Online radio:: You can add you own online radio
NOTE: You need to add the url of the online audio stream (don´t confuse with the url of the radio web player).

Turn off WiFi after lullaby:: Turns off the WiFi signal once the volume reaches zero. For online radios and streaming services.

== Advanced Options
[horizontal]
Binaural beats::
* Delta - frequency goes down to 2 Hz
* Theta - frequency goes down to 4 Hz
NOTE: Effective only if you use the lullaby with headphones
NOTE: We do strongly discourage users from using binaural beats if they suffer epileptic or cardiac issues!
Volume:: Set a volume of binaural tones
Binaural beats in alarm:: Configures stimulating binaural beats into alarm sounds
* Beta - frequency around 20 Hz
* Gamma - frequency around 40 Hz
Mindroid::
https://play.google.com/store/apps/details?id=com.urbandroid.mind[Mindroid]

___

== How to
// TODO
[horizontal]
Use podcast / audiobook::

== Troubleshooting

