---
layout: default
title: Sleep tracking
nav_order: 2
has_children: true
// parent: Sleep - basic features
---
:toc:


## What it does
.Sleep tracking is a way to objectively measure the quality of your sleep.

By tracking your sleep, the app enables you to:

. See a sleep graph for every night
. Monitor your long term sleep quality (with link:/docs/theory/sleepscore.html[sleep score] and statistics)
. Set up goals to improve your sleep quality
. Use link:../alarms/smart_wake_up.html[smart wake up] for the alarm

TIP: link:../theory/sleep_tracking_theory.html[Go here for a more in-depth read on sleep tracking].

## Where to find it
Start sleep tracking on the app's main screen by tapping *Start sleep tracking*.

Settings can be found in
*Sleep as Android > Settings > Sleep tracking*.

## Options
[horizontal]
Smart wake up:: See link:../alarms/smart_wake_up.html[Smart wake up]
Awake detection:: See [Awake detection]

.Automatic sleep tracking
[horizontal]
Start sleep tracking:: Set to something other than _Manual only_ to enable automatic sleep tracking start.
- More details: link:automatic_sleep_tracking.html[Automatic sleep tracking].
Sleep time estimate:: Do you forget to track your sleep? Enable this to receive sleep length estimates in a notification every day without you doing anything.
- On _Manual only_, you'll receive a notification that you have to confirm in order to create the sleep record
- On _Save automatically_, the notification saves the sleep record for you automatically
- More details: link:sleep_time_estimation.html[Sleep time estimation]

.Sensor
[horizontal]
Sensor:: Choose a sensor that will be used for motion tracking when you track using phone (ie. without wearables or Sleep Phaser).
Test sensor:: Test if your chosen sensor (sonar or accelerometer) is working correctly. May not work with all integrated wearables.
Tutorial:: ...

.Pair tracking
[horizontal]
Pair tracking:: Check to enable pair tracking. More details: link:../sleep_advanced/pair_tracking.html[Pair tracking].
Find partner:: Tap simultaneously on two phones that are close together to form a pair.

.Do not disturb when sleeping
[horizontal]
Do not disturb when sleeping:: If checked, do not disturb (DND) mode will be enabled during sleep tracking, and disabled again when sleep tracking ends.
Note the following special rules:
- if DND was active before sleep tracking started, Sleep will not touch it (ie. it won't disable it in the morning)
- if DND was activated by Sleep, but you have toggled it during the sleep tracking, Sleep will not touch it again
Turn off wireless signal during sleep::
This option tries to disable radios (wifi, cellular) during sleep tracking. Due to constraints gradually introduced in Android, it behaves differently based on the Android version you have on your phone.
Below 4.2: turns on airplane mode
Lollipop (5): turns off wifi
Oreo (8): turns off wifi. If you have turned on airplane mode manually, we cannot turn wifi on for features such as IFTTT or Smartlights
Q (10): does nothing - Android 10 has removed any means of controlling wifi programmatically

.Advanced
[horizontal]
Screen dimming:: Control what will happen to the phone screen while sleep tracking.
  Disabled::: Sleep does nothing, your system screen timeout applies
  Dim::: Screen dims, your system screen timeout applies
  Dim with clock::: Screen dims, shows time, your system screen timeout applies
  Always on clock::: Screen dims, shows time, your system timeout DOES NOT apply
Hide stats before rating:: By default statistics are shown in the morning after sleep tracking ends. If you think the statistics might influence how you'd rate the night, turn this on.
Stand-by:: Sleep tracking will be put into standby mode when battery drops under level set here. No further sleep data will be collected. This saves battery for the alarm.
Battery optimized:: This option will enable accelerometer sensor batching, if it is available on your phone. This means that the phone does not have to have CPU awake all night to be able to read data from the sensor.
WARNING: Due to Doze mode, starting from Android 6 we need to schedule a user-visible alarm every minute to be able to use sensor batching. This alarm will never ring, but will be visible on your status bar/lockscreen.
// Read more about the problem here: //TODO: zjistit jak to je



// ## Guide

## Troubleshooting