---
layout: default
title: Advice
nav_order: 2
parent: /docs/theory/theory.html
---
:toc:

== What it does
Advice shows your current sleep development at a glance. You see which dimensions of your sleep have improved or worsened recently including tips on how to reverse the worsening trends.

== Where to find it
*Left ☰ menu -> Advice* or from the <</docs/homescreen#advicecard,Advice>> dashboard card.

== General description
Advice watches recent trends in the main sleep dimensions (Duration, Irregularity, Deep sleep %, Snoring, Social jet-lag...).

In most cases it compares your last 60 days aggregates to the last 7 days aggregates and look for significant recent worsening or improvements.

For some dimensions there are further checks, such as whether your data are within bounds set by public health studies.
//
//For some dimensions there are checks to be within bounds set by public medical studies.
//
//Advice also looks at your tags and tells you when there is an increased occurrence of e.g. #alcohol as a caution or #sport as good trend.
//
//Advice also compares your sleep figures with the average data measured by the app for your peers in your country.

== Watched dimensions


|===
|Dimension |Checks

|Duration
a|* Has it recently improved or worsened? (last 7 days compared to last 60 days).
* Is it in healthy bounds for your age? General (6.5 - 9), school age (9 - 11), teenager (8 - 10), young (7 - 9), elderly (6 - 9).
* Does it meets your <</docs/ideal_daily_sleep#,Ideal daily sleep>> target?
* How does it compare to others in your country?


|Irregularity
a|* Has it recently improved or worsened? (last 7 days compared to last 60 days)
* Is it in healthy bounds for last 60 days average (1 hour - 20 minutes)?
* How does it compare to others in your country?

|Deep sleep %
a|* Has it recently improved or worsened? (last 7 days compared to last 60 days).
* Is it in healthy bounds for last 60 days average (25% - 75%)?

|Snoring
a|* Has it recently improved or worsened? (last 7 days compared to last 60 days).
* Warns if over 30 minutes, and a more severe warning over 60 minutes.
* How does it compare to others in your country?

|Social jet-lag
a|* Is it in healthy bounds for last 60 days average (1 hour - 20 minutes)?

[NOTE]
===
Your age for the duration healthy bounds can be configured in _Settings -> Sleep -> Stats -> Year of birth_
===

|===

== Types of advice cards

[horizontal]
Congrats:: Shows an improvement in a given dimension.
Caution:: Shows a worsening with tips on how to improve and links to setup <</docs/sleep_advanced/goals#,Goals>>.
Neutral:: Not clearly a positive or negative message. E.g. if other people in your country are getting less sleep it is not directly a positive or negative message. Or if your custom tag e.g. #work is occurring a lot lately we cannot say it is good or bad.

== Examples

Congrats:: Your SNORING is down by 5 minutes lately
Caution:: Your DURATION is down by 30 minutes lately
Neutral:: Others in your country are getting 54 minutes more DURATION
Caution:: Your SNORING is over 50 minutes
Congrats:: Your IRREGULARITY is under 20 minutes
