---
layout: default
title: Smartlight
nav_order: 2
parent: /docs/connected_devices/connected_devices.html
---
:toc:

== What it does
*Uses your smartlight to enhance your sleep experience*

Features:

- Sunrise-like wakeup
- Pee-light
- Jet lag prevention with light
- Lucid dreaming and anti-snoring cues with light

== Where to find it
_Settings -> Smartlight_

== Options
[horizontal]
Use smartlight:: Enables smartlight support
Maximum intensity:: Set a global limit for brightness a smartlight would be allowed to achieve when controlled by Sleep. This is useful for sunrise alarm where 100% might be too bright for some people.

.Alarm
[horizontal]
Keep light up after:: Set whether the light should stay on after dismissing alarm, snoozing alarm or both. Or none.
Use screen light:: Enable to use your phone's screen as a smartlight for the sunrise alarm.
Wake up with flashlight:: If enabled, your phone's flashlight will be flashing during alarm.
WARNING: Might be unreliable on some phones.

.Miscellaneous
[[Miscellaneous]]
[horizontal]
Pee-light:: If this is set, a pause in sleep tracking will turn on a red light on your set smartlight. If this is set to "Tracking is paused", the pee-light will be on for the whole pause.
Lucid dreaming:: Use smartlight as a cue for lucid dreaming. When your REM phase is detected, your set light will flash.
Anti-snoring:: Use smartlight as a cue for anti-snoring. When snoring is detected, your set light will flash. See

.Philips HUE, IKEA Tr책dfri
[horizontal]
Philips HUE, IKEA Tr책dfri (disconnected):: Tap this to connect your HUE or Tr책dfri.
Test:: Test connection to your bulb by flashing it.
Turn off:: Force turning off your connected bulb.

.Sleep Phaser
[horizontal]
Sleep Phaser (disconnected):: Tap this to connect to your link:http://sleepphaser.urbandroid.org/[Sleep Phaser].
Smartlight:: Use your connected Sleep Phaser as a smartlight. Sleep Phaser doesn't care about the topmost "Use smartlight" setting in this category.
Sleep tracking:: Use your connected Sleep Phaser's PIR sensor as a sensor for sleep tracking.
Start automatically:: Start tracking automatically when you start charging your phone while your Sleep Phaser is in Bluetooth range.
NOTE: On Android 8 and later, you need to have link:https://play.google.com/store/apps/details?id=com.urbandroid.watchsleepstarter[Watch / Phaser Starter for Sleep as Android] installed in order for this to work.

For complete manual for Sleep Phaser, see <</docs/connected_devices/sleep_phaser,Sleep Phaser>>.

.Sleep Mask
[horizontal]
Use Sleep Mask:: Enable to use your link:https://www.happy-electronics.eu/shop/en/home/32-sleep-mask-for-sleep-as-android.html[Sleep Mask] as a smartlight.

== Guide

=== How to setup sunrise alarm (sunrise-like wakeup) ?
[[sunrise_alarm_guide]]
. Enable _Settings -> Smartlight -> Use smartlight_
. Select your smartlight:
* Use phone's screen as a smartlight: Enable _Smartlight -> Use screen light_
* Use a smartbulb as a smartlight: Connect using _Smartlight -> Philips HUE, IKEA Tr책dfri (disconnected)_
* Use Sleep Phaser as a smartlight: Connect using _Smartlight -> Sleep Phaser (disconnected)_ and enable _Smartlight_ right under it.

After you've done the above steps to connect and enable the smartlight of your choice, all of your alarms will turn on the smartlight when they start ringing. Now, to have a truly sunrise wakeup, you probably want the smartlight to turn on _before_ the alarm rings.

To set that up, head to _Settings -> Alarms -> Alarm sound start_ and set it to some period. At the time of the alarm, only the smartlight will turn on at the lowest brightness and gradually brighten up until the set period passes. Then the alarm starts ringing.
