---
layout: default
title: Alarm settings
nav_order: 2
parent: /alarms/0parent.html
tags:
- alarm
---
:toc:

== What it does
*Alarm settings help you make your wakeup alarm a refreshing and pleasant experience.*

Most of all:

* <</alarms/smart_wake_up#,Smart wake up>> wakes you at the right sleep phase
* <<gentle_alarm, Gentle volume increase>> finds the minimal sound to wake you
* <</devices/smart_light#,Smartlight>> natural sunrise wake up
* and many more.

We make sure even sleepyheads wake up on time with our <</alarms/captcha#,CAPTCHA>> feature.

== Where to find it
Alarms can be setup in two places. Each alarm has its own alarm-specific settings. Newly created alarms are by default based on _Settings -> Alarms_.

Alarm-specific settings[[per-alarm]]::

Alarm-specific settings change behaviour of a particular alarm; those changes won't affect other alarms or default settings.

Default settings in  _Settings -> Alarms_::
Alarm default settings allow you to modify basic behaviour for all your alarms. Default settings are also applied to all new alarms.

== Options

[horizontal]
Ringtone:: See <</alarms/ringtone#,Ringtone>>.
Gentle volume increase[[gentle_alarm]]:: Gentle volume makes sure to wake you with minimum volume required for a more pleasant wake up. Alarm starts at minimum volume and will gradually increase to maximum.
* Disabled - Alarm rings at system's alarm stream volume (or media stream when using streaming services or changing the _Alarm output_ settings). For more details see the <</alarms/ringtone#,Ringtone>> section.
* 1-24 minutes - Sets how long it takes to reach the max volume; the longer the period, the slower the volume increases and the longer it takes to reach the max.
Vibrate:: Enables phone vibrations (do not confuse with vibrations on wearable).
* Disabled - No vibrations on phone at all.
* From start - Vibrations start at alarm time.
* After 1-24 minutes - Vibrations start after set time.
Alarm sound start::
You may want to first give chance to <</devices/smart_light#,Smartlight>> or vibrations to wake you up, before the alarm starts sounding.
* From start - Sound starts at alarm time.
* 1-24 minutes - Sounds starts after set time.
Play alarm in silent profile:: Alarm sound will override phone's silent mode.

.Snooze / Dismiss
[horizontal]
Snooze:: See <</alarms/snooze#,Snooze>>.
Always fullscreen alarm:: Alarm will never show up as a heads-up notification. This includes Android 10 where this feature requires the _Draw over other apps_ permission.
Flip to snooze:: Lets you snooze an alarm by flipping the phone (from screen to back and other way around).
Volume or camera button effect:: Allows to snooze or dismiss the alarm with volume buttons.
No screen orientation changes:: Prevents changes of screen orientation while the alarm rings (prevents accidental snoozes or dismiss during orientation changes).
Long press:: Long press on dismiss button is necessary to dismiss the alarm (prevents accidentally dismissed alarms).

.Backup alarm
[horizontal]
Backup alarm:: See <</alarms/backup#,Backup alarm>>.
Alarm timeout:: See <</alarms/backup#,Backup alarm>>.

.Dangerous options
[horizontal]
Alarm output:: Can force the alarm sound output to media stream, so the alarm is audible only in your headphones (not through the device speaker).
NOTE: Please, test it before using it, on some devices the alarm output may be silenced due to DND or other settings.
Alarm reliability:: Can increase reliability of the alarm on problematic phones (see https://dontkillmyapp.com?app=Sleep%20as%20Android[dontkillmyapp.com]).

.Alarm-specific settings
All default options are also available as alarm-specific options.

There are also few options that are only available in alarm-specific settings:
[horizontal]
Repeat:: Set a schedule for repeating alarm, you can choose also <<even_odd,Even / odd bi-weekly patterns>>.
Delete after ringing:: Deletes this alarm completely after dismiss (useful for one-time alarms).
Terminate tracking:: Enabled by default. Normally dismissing an alarm will end current sleep tracking. Disable this to continue tracking even after you dismiss the alarm.
Silent alarm (in Ringtone):: Sets an alarm without sound.

== Guide
[horizontal]
Create alarm only as vibrations on watch (no sound)::
. Set the alarm silent (_<<per-alarm,Alarm-specific settings>> -> Ringtone -> Silent_) or set the delay on sound (_Settings -> Alarms -> Sound delay_).
. Enable wearable vibrations (_Settings -> Wearables -> Vibrate_).
+
NOTE: We highly recommend to set a sound delay instead of setting the alarm silent, especially when backup alarm is silent too.

Create silent alarm::

. Set the alarm silent (_<<per-alarm,Alarm-specific settings>> -> Ringtone -> Silent_).
. This option is available only in <<per-alarm,Alarm-specific settings>>, not in _Settings -> Alarms_. This is a safety measure to prevent unintentional silent alarms.
+
NOTE: We highly recommend to set a sound delay instead of setting the alarm silent, especially when backup alarm is silent too.
Postpone next alarm::
. Open alarm -> Postpone next alarm.
. Use the sliding bar or the drop down menu list for postponing alarm.
. Confirm the alarm time change.
+
NOTE: Works only for repeating alarms.
Skip next alarm::
. Open an alarm -> Skip next, confirm the change.
. Or long press on the alarm on alarm board -> Skip next.
+
NOTE: Works only for repeated alarms.
+
NOTE: Skip next through long press can be used repeatedly, so that you can skip several days in advance.
Dismiss alarm before alarm time::
. Open before alarm notification (appears one hour before alarm) from the notification bar on your phone.
. Dismiss from the notification.
+
NOTE: Won't deactivate the alarm completely, so it has no effect on next alarms.
Use my own sound as alarm::
. Open Ringtone selection: _Settings -> Alarm default settings -> Ringtone_ or _<<per-alarm,Alarm-specific settings>> -> Ringtone_.
. Tap on folder icon:ic_folder[] icon in right upper corner.
. Choose a sound file saved on your phone.
+
NOTE: In the file picker you may first need to enable showing of external storage to be able to see your sound there.
Name an alarm::
. Open an existing alarm details screen or create new alarm dialogue.
. Name your alarm in the Label field in upper right corner. You will see this name on the alarm dialog in the morning, so you can use it for TODOs or motivation texts and they will be written into your sleep graph description.
Create odd / even schedule:: [[even_odd]]
. Open _<<per-alarm,Alarm-specific settings>>_.
. Choose Repeat dialogue (_Repeat:Never_ or days of week listed below alarm time).
. Choose Weekly / Even / Odd pattern from the drop down menu list.
