---
layout: default
title: Backup alarm
nav_order: 2
parent: /alarms/0parent.html
tags:
- backup
---
:toc:

== What it does
*Starts ringing loudly on maximum volume if you ignore your normal alarm.*

Backup alarm starts after <<alarm-timeout,Alarm timeout>>.

== Where to find it
_Settings -> Alarm default settings -> Backup alarm_

== Options
[horizontal]
Backup alarm duration:: Set for how long will the backup alarm ring (after that it gets snoozed for your default _Snooze time_, but never less than 10 minutes.
Ringtone:: Backup alarm ringtone.
NOTE: Backup alarm can also be set to silent.
Alarm timeout [[alarm-timeout]]:: Time after which the backup alarm will ring if you ignore your normal alarm.
Repeat:: Maximum time of repeats – after that, no alarm will ring anymore.
+
[EXAMPLE]
====
Alarm time: 7:00
Backup alarm duration: 2 minutes
Alarm timeout: 10 minutes
This is what happens when you don’t interact with the alarm:

- 7:00 – alarm starts
- 7:10 – backup alarm starts (full volume, duration 2 min)
- 7:12 – automatically snoozes (for 10 minutes as your default snooze time is 10 minutes)
- 7:22 – backup alarm starts again

…and so on, based on the number of repeats.
====

== How to disable it

[horizontal]
How to disable backup alarm::
. Go to _Settings -> Alarm default settings -> Back up -> Ringtone_.
. Set the ringtone to _Silent_.
