---
layout: default
title: Captcha
nav_order: 2
parent: /alarms/0parent.html
tags:
- captcha
---
:toc:

== What it does
*Gives you a task to solve in order to dismiss the alarm.*

CAPTCHAs make sure you wake on time and won't be late for your daily duties. CAPTCHAs prevent any unintentional alarm dismiss.

== Where to find it

- _Settings -> CAPTCHA: Stop oversleeping!_
- _<</alarms/alarm_settings#per-alarm,Alarm-specific settings>> -> CAPTCHA: Stop oversleeping!_

NOTE: CAPTCHA can also be configured in <</alarms/alarm_settings#per-alarm,Alarm-specific settings>>. You can override your default CAPTCHA settings on each alarm and use a more difficult CAPTCHA on special occasions (e.g. exams) or an easier CAPTCHA on the weekends.

== Options
[horizontal]
Default CAPTCHA:: CAPTCHA for all alarms (that are not overridden by <</alarms/alarm_settings#per-alarm,Alarm-specific settings>>)
CAPTCHA Difficulty:: Sets CAPTCHA difficulty. How is difficulty used depends on each CAPTCHA. E.g. Math CAPTCHA requires you to do more equations with larger numbers on higher difficulty.
Preview:: See the selected CAPTCHA in action.
WARNING: We strongly recommend to test each CAPTCHA with the _Preview_ feature and use _Settings_ before it is used in the morning - that could bring unwanted surprises.
Settings:: Some CAPTCHAs have addition settings, e.g.:
 * Editing, adding, and deleting QR codes and NFC tags
 * Selecting tasks for MultiCaptcha
 * Choosing your mantra for Mirror Text CAPTCHA
CAPTCHA Cheating protection:: Prevents avoiding solving the CAPTCHA, see <<Cheat,Cheating protection>> details

CAPTCHA ADD-ons:: Download a free extension with more CAPTCHA tasks from https://play.google.com/store/apps/details?id=com.urbandroid.sleep.captchapack[Play Store]

.Advanced Options
[horizontal]
Alarm volume in CAPTCHA:: Lowers or mutes the alarm volume while solving a CAPTCHA task
NOTE: During CAPTCHA solving, alarm volume is lowered for 1 minute so that you don’t wake your partner with the ongoing alarm. You can use the 1 minute either to solve the CAPTCHA or get to a different room for solving it.
To get more time, tap on the _+_ icon in the upper right corner

== Guide

=== CAPTCHA types

.Built-in CAPTCHAS
[horizontal]
Simple math:: Select the correct answer to a math problem from a list of 4 answers
Typed math:: Type the correct answer to a math problem without a hint
Sleeping sheep:: Find an awake sheep
QR code:: see <<QR_NFC,QR Captcha>>
NFC tag:: see <<QR_NFC,NFC Captcha>>
Shake it::  Shake your phone
Dream diary:: Write down your dream (10 characters minimum at Difficulty 1).
NOTE: Dream diary entries are saved into your sleep record comments. If there is no sleep record, they are only saved into your clipboard - this allows you to paste them somewhere else.
Say cheese!:: Smile to your front camera, with more difficulty you need a cast a more charming smile!
Laugh Out Loud:: Laugh at your phone microphone

.CAPTCHA pack
[horizontal]
Captcha Captcha:: Classic CAPTCHA known from the early internet days - type the letters of a distorted image
Random Captcha:: Solve up to 5 different tasks each morning
Multi Captcha:: Solve up to 15 chosen tasks in a row
Mirror text:: Read and type a text from a mirror-flipped quote - pre-defined or your own (configured in _Settings -> Captcha -> Settings_)
Swearing:: Swear your way to dismiss (English only)
Zombie Walk:: Walk 14-74 meters with the phone
Let there be light:: Put your phone to a light source
Fun with Flags:: Recognize flags
Spin around:: Spin around while keeping thumbs on the buttons on the screen

=== QR code and NFC tag CAPTCHA
[[QR_NFC]]
The QR and NFC CAPTCHAs are the ultimate solution for waking up. You can place a QR code or NFC tag in your bathroom or kitchen. The alarm than won’t stop until you get out of bed and scan the code/tag.

[horizontal]
QR CAPTCHA:: You can use any barcode or QR code (there are many free online QR code generators).
WARNING: The option Power off protection cannot be used with 3rd party scanning apps
NFC CAPTCHA:: You can use any credit card, some membership cards or ID cards.
NOTE: For security reasons, NFC Captcha requires unlocking the screen first
Only at home:: Allows you to skip CAPTCHA when not at home.
NOTE: Your location must be significantly different from your home (at least 2.5 km), as the app does not collect fine location information
Must scan all codes:: You need to scan all saved codes.

supported QR apps are Barcode Scanner, QRDroid, Google Goggles

[horizontal]
Learn new QR code / NFC tag::
. Go to _Settings -> Captcha -> Settings_
. Tap on "Learn"
Delete a QR code / NFC tag::
. Go to _Settings -> Captcha -> Settings_
. Tap on the trash can icon:ic_action_discard[]

=== CAPTCHA cheating protection
[[Cheat]]
There are three ways of protecting the alarm from your devious morning self:

==== Power off protection
Power off protections hides power-off dialogue, so you cannot restart the device or turn it off.


NOTE: Power off protection will overlay the screen, preventing you to cheat the tasks. You cannot use 3rd party scanners (for QR Captcha) with this option.

==== Wakeup motivation
This option allows you to set a small wager on not cheating the Captcha. This will boost your motivation to wake up!
The wager is refundable anytime directly from the app by using the REFUND button.
If you cheat the Captcha, the wager is lost.

==== Force stop and uninstall protection
This advanced option grants the app admin privileges to prevent uninstalling the app.
Admin privileges also prevent the system from clearing the app's data.

NOTE: To uninstall the app or to clear the app's data, you need to revoke this option!

