---
layout: default
title: Ringtone
nav_order: 2
parent: /alarms/0parent.html
tags:
- ringtone
---
:toc:

== What it does
*Changes how will your alarm sound.*

Choose any music or sounds from a built-in nature sounds library, from your local device storage or use online radios or streaming services such as Spotify for even more enjoyable mornings.*

== Where to find it
_Settings -> Alarm default settings -> Ringtone_

== Options

[horizontal]
Silent:: Available only in <</alarm_settings#per-alarm, Alarm-specific settings>>. Won't turn off vibrations.
Single ringtone:: You can choose a single ringtone or multiple ringtones to create a playlist (see below).
+
NOTE: When you choose a sound, you will hear the preview.
+
Playlist:: Tap on the playlist icon in top right icon:ic_action_view_as_list[] and choose files to create your own playlist.
Browse your local files:: Tap on the folder icon icon:ic_folder[] and select your files from your internal or external storage. The system file picker will show up and you may need to enable external storage access first before you can see it in the picker.
Online radio[[radio]]:: You can add any radio you want, if you provide the stream URL (do not confuse with radio URL). Few SomaFM radios are added by default.
Available online radios:
- Ancient FM - https://www.gofundme.com/f/ancientfm-2021[a community funded radio station]
- Bagel Rock
- Beat Blender
- Chillout Lounge
- Covers
- Folk Salad
- Groove Salad
- Illinois Street Lounge
- Lush
- Sleep Pill
- Sonic Universe
- Space station
- Underground 80s

+
NOTE: In the morning, Sleep turns on the Wifi automatically and waits for 30 seconds while trying to establish the connection. If it can’t play radio, it plays the local ringtone.
+

Spotify playlist:: You can add your saved albums or playlists from Spotify’s _Your Library > Albums / Playlists_

Other playlists (including Google Play Music playlists):: Lots of media player apps can create such playlists from music that is available on your phone.

//#TODO: really?#

== Guide

[horizontal]
How to create your own playlist::
. Open Ringtone selection and tap on the icon:ic_action_view_as_list[] in the upper right corner.
. Now select any combination of the available ringtones.
. Choose the order (Shuffle / Order / Loop single) in the ⋮ menu in upper right corner.
. Confirm the selection with "OK" button or icon:ic_action_accept[].
* See a video guide

+
video::Dr9EnzTFHY4[youtube]
+

How to add my own song, sound file::
. Tap on the folder icon icon:ic_folder[] in the upper right corner.
. Select a file in your file browser
. Make sure the file is available and the app has permission for accessing that folder.
* See a video guide

+
video::TWXKkFV2zS4[youtube]
+

