---
layout: default
title: Ringtone
nav_order: 2
parent: /alarms/alarms.html
tags:
- ringtone
---
:toc:

== What it does
*Changes how will your alarm sound of alarm(s).*

Choose any music or sounds from a build-in nature sounds library, from your local device storage or use online radios or streaming services such as Spotify for even more enjoyable mornings.*

== Where to find it
_Settings -> Alarm default settings -> Ringtone_

== Options

[horizontal]
Silent:: Available only in <</alarm_settings#per-alarm, Alarm-specific settings>>. Won't turn off vibrations.
Single ringtone:: You can choose a single ringtone or multiple ringtones to create a playlist (see below).
Playlist:: Tap on the playlist icon in top right icon:ic_action_view_as_list[] and choose files to create your own playlist.
Browse your local files:: Tap on the folder icon icon:ic_folder[] and select your files from your internal or external storage. The system file picker will show up and you may need to enable external storage access first before you can see it in the picker.
Spotify playlist:: You can add your saved albums or playlists from Spotify’s _Your Library > Albums / Playlists_
Other playlists (including <</faqs/google_play_music,Google Play Music>> playlists):: Lots of media player apps can create such playlists from music that is available on your phone.
File-based playlists:: You can use any file-based playlist (.m3u, .pls) you have on your phone.

#TODO: really?#

== Guide

[horizontal]
How to create your own playlist::
. Open Ringtone selection and tap on the icon:ic_action_view_as_list[] in the upper right corner.
. Now select any combination of the available ringtones.
. Choose the order (Shuffle / Order / Loop single) in the ⋮ menu in upper right corner.
. Confirm the selection with "OK" button or icon:ic_action_accept[].
How to add my own song, sound file::
. Tap on the folder icon icon:ic_folder[] in the upper right corner.
. Select a file in your file browser
. Make sure the file is available and the app has permission for accessing that folder.
