---
layout: default
title: Garmin
nav_order: 7
parent: /devices/wearables.html
tags:
- garmin
- wearable
---
:toc:

Sleep as Android integrates Garmin wearables that support the ConnectIQ (CIQ) platform.

Does your watch support the ConnectIQ platform? https://developer.garmin.com/connect-iq/compatible-devices/[check here].

[WARNING]
We are doing our best to provide a full featured integration for all the different wearable platforms, but on some platforms it is really hard due to various limitations in their APIs.
We have asked Garmin to give us access to their BT specific API for the good of our users and theirs, but they refused or asked for a huge amount of money to do so.
So we have to rely on the buggy IQConnect API with problems that Garmin has not fixed for many years. Because their message queue breaks regularly, we had to implement our own parallel messaging system using HTTP.
This makes the Garmin integration far from optimal and severely limits our ability to fix problems. The integration is provided "as is".

== How to set up
You will need to install the following apps:

.On the phone
. https://play.google.com/store/apps/details?id=com.urbandroid.sleep.garmin[Garmin Addon for Sleep as Android] from Play Store.
. https://play.google.com/store/apps/details?id=com.urbandroid.watchsleepstarter&hl=en_US[Sleep Watch starter] from Play Store.

.On the watch
. Install the current version of the watch app https://apps.garmin.com/en-US/apps/e80a4793-f5a3-44c7-bd7f-52a97f5d8310[thourgh the ConnectIQ Store] (Connect IQ 3.1 and higher).
. Make sure that all of the apps are installed, and then select _Sleep -> Settings -> Sleep tracking -> Wearables -> Use wearables -> Garmin_.
. For HR data, enable *Heart rate monitoring* in _Settings -> Sleep tracking -> Wearables_.
. To start sleep tracking with your watch, tap _Start tracking_ on the <</ux/homescreen#,Homescreen>>.

.If you have troubles with muted vibrations for lucid cues or anti-snoring alerts
. On your wearable go to _Settings -> System -> Sleep mode_ and disable *DND while sleep*.
. Make sure *Status notification* and *Allow vibrations* are enabled on the wearable in _Settings > Smart notification > notifications > Overall usage and apps > Apps_

WARNING: You need to side-load a legacy version of the Sleep app, if your ConnectIQ is less than 3.1. https://sleep.urbandroid.org/more/garmin-legacy-watch-app-downloads/[Look here], find your model and put the corresponding file (Sleep.prg) onto your device, in /GARMIN/APPS folder


NOTE: Garmin integration does not support testing the sensor with <</sleep/sleep_tracking#test_sensor,Test sensor>>.

WARNING: On some watches (mainly Vivoactive 3) there is a long-standing firmware issue that prevents you from accepting the starting dialog on the watch. Please start tracking from the watch instead. See <</faqs/garmin_start_dialog_bug#,FAQ: Garmin - Cannot accept start dialog (green tick)>>

== Supported watches

https://raw.githubusercontent.com/urbandroid-team/Sleep-as-Android-Garmin-Addon/master/SleepGarmin-watch2/manifest.xml[List of supported Garmin wearables].

* Garmin Approach S70 42mm, Approach S70 47mm
* Garmin D2 air, D2 Airx10, D2 Delta, D2 Delta PX, D2 Delta S, D2 Mach1
* Garmin Descent G1, Descent Mk2, Mk2S
* Garmin Enduro
* Garmin Epix 2, Epix 2PRO 42mm, Epix 2PRO 47mm, Epix 2PRO 51mm
* Garmin fēnix 5, fēnix 5 Plus, fēnix 5S, fēnix 5S Plus, fēnix 5X, fēnix 5X Plus
* Garmin fēnix 6, fēnix 6 Pro, fēnix 6S, fēnix 6s Pro, fēnix 6x Pro
* Garmin fēnix 7, fēnix 7 Pro, fēnix 7S, fēnix 7S Pro, fēnix 7X, fēnix 7X Pro, fēnix Chronos
* Garmin Forerunner 165, Forerunner 165M
* Garmin Forerunner 245, Forerunner245M
* Garmin Forerunner 255, Forerunner 255M, Forerunner 255D, Forerunner 255SM
* Garmin Forerunner 55
* Garmin Forerunner 645, Forerunner 645M
* Garmin Forerunner 265, Forerunner 265S
* Garmin Forerunner 745,
* Garmin Forerunner 935
* Garmin Forerunner 945, Forerunner 945 LTE
* Garmin Forerunner 955, Forerunner 955 LTE
* Garmin Forerunner 965
* Garmin Instinct 2, Instinct 2S, Instinct Crossover, Instinct 2X
* Garmin Legacy Hero Captain Marvel, First Avenger
* Gamin Legacy Saga Darth Vader, Rey
* Gamin MARQ Adventurer, MARQ Athlete, MARQ Aviator, MARQ Captain, MARQ Commander, MARQ Driver, MARQ Expedition, MARQ Golfer, MARQ2 Aviator
* Garmin Venu, Venu 2, Venu 2 Plus, Venu 2S, Venu D, Venu SQ, Venu SQ2, Venu SQM, Venu SQ2M
* Garmin vívoactive 3, vívoactive 3M, vívoactive 3M LTE, vívoactive 4, vívoactive 4S, vívoactive 5
