---
layout: default
title: Garmin
nav_order: 50
parent: /devices/wearables.html
tags:
- garmin
- wearable
---
Sleep as Android integrates Garmin wearables that support the ConnectIQ (CIQ) platform.

Does your watch support the ConnectIQ platform? https://developer.garmin.com/connect-iq/compatible-devices/[check here].

== How to set up
You will need to install the following apps:

For the phone:

. https://play.google.com/store/apps/details?id=com.urbandroid.sleep[Sleep as Android] on the phone
. https://play.google.com/store/apps/details?id=com.urbandroid.sleep.garmin[Garmin Addon for Sleep as Android] on the phone

For the watch:

* If your watch supports ConnectIQ at least 3.1, install the current version of the watch app:
- https://apps.garmin.com/en-US/apps/e80a4793-f5a3-44c7-bd7f-52a97f5d8310[link to the app] (install through the ConnectIQ Store in Garmin Connect app)
* If your watch isn't being updated anymore by Garmin and supports only ConnectIQ version less than 3.1, you will need to sideload a legacy version of the Sleep app:
- https://sleep.urbandroid.org/more/garmin-legacy-watch-app-downloads/[look here], find your model and put the corresponding file (Sleep.prg) onto your device, in /GARMIN/APPS folder

Make sure that all of the apps are installed, and then select _Sleep -> Settings -> Wearables -> Use wearables -> Garmin_.

To start sleep tracking with your watch, tap _Start tracking_ on the <</ux/homescreen#,Homescreen>>.

WARNING: Garmin integration does not support testing the sensor with <</sleep/sleep_tracking#test_sensor,Test sensor>>.

WARNING: On some watches (mainly Vivoactive 3) there is a long-standing firmware issue that prevents you from accepting the starting dialog on the watch. Please start tracking from the watch instead. See <</faqs/garmin_start_dialog_bug#,FAQ: Garmin - Cannot accept start dialog (green tick)>>

== Supported watches

{% for wearable in site.data.wearables %}
  {% if wearable['Support /<br>sensors'] contains 'YES' and wearable.Vendor == 'Garmin' %}
    * +++ {{ wearable.Vendor }} - {{ wearable.Device}} +++
  {% endif %}
{% endfor %}

== Unsupported watches
NOTE: This list may not be exhaustive.

{% for wearable in site.data.wearables %}
  {% if wearable['Support /<br>sensors'] contains 'NO' and wearable.Vendor == 'Garmin' %}
     * {{ wearable.Vendor }} - {{ wearable.Device}}
  {% endif %}
{% endfor %}
