---
layout: default
title: Samsung Gear / Galaxy Gear
nav_order: 6
parent: /devices/wearables.html
tags:
- samsung
- gear
---
:toc:

Sleep as Android supports most Samsung wearables, but not all. Please look for your device in <<supported-watches>> below.

## How to set up
. First, install all the required parts - the Samsung Galaxy Gear integration consists of three parts:
+
- https://play.google.com/store/apps/details?id=com.urbandroid.sleep[Sleep as Android] on the phone
- https://play.google.com/store/apps/details?id=com.urbandroid.sleep.addon.generic.samsung[Sleep as Android Gear Addon] on the phone
- https://galaxy.store/sle[Sleep as Android - Native Gear Companion] on the watch (install through the Galaxy Gear Store)

+


. Now, you can enable the connection in _Settings -> Sleep tracking -> Wearables -> Use wearable -> Samsung Gear / Galaxy Watch_.
. Then test the connection in _Settings -> Sleep tracking -> Wearables -> Test sensor_ - you should see a graph reacting to your movement (a short delay is normal, data are sent in batches).

## How to set up Gear Fit 2


WARNING: Galaxy Store suspended our wachface for Gear Fit, and we have to pass their new verification process. The watchface is currently not available. We are sorry for the inconvenience.


Samsung Gear Fit 2 is the only exception - to track sleep using Gear Fit 2 with Sleep as Android, you have to install and set up our addon on the phone and our app on the watch (actually a watchface).

The steps to follow are:

. Install https://play.google.com/store/apps/details?id=com.urbandroid.sleep.addon.generic.samsung[Sleep as Android Gear Addon] on the phone.
. Install https://galaxystore.samsung.com/geardetail/com.urbandroid.sleep.gearfit[Sleep as Android for Gear Fit 2 watch face] on the Galaxy Store using your Galaxy Wearable app.
. Now, you can enable the connection in _Settings -> Sleep tracking -> Wearables -> Use wearable -> Samsung Gear / Galaxy Watch_.
. Then test the connection in _Settings -> Sleep tracking -> Wearables -> Test sensor_ - you should see a graph reacting to your movement (a short delay is normal, data are sent in batches).

NOTE: Whenever you want to do sleep tracking, switch the watchface on your Gear Fit 2 to the Sleep watchface, and double tap to start tracking. It would actually work even without switching to the watchface (so you can start tracking from the phone), but you won't have any way to stop it from the watch, and alarm will have to be stopped from the phone in that case. So I recommend switching to the Sleep watchface.
To switch the watchface, just long tap on the current watchface.

If you are interested in some background stories and explanations on why it works this way, check out https://sleep.urbandroid.org/sleep-%E2%9D%A4-gear-fit-2/[this link] or for more technical information check out https://medium.com/@roundedeverett/how-to-develop-apps-for-samsung-gear-fit-2-16119801da1b[this link].

## Supported watches

{% for wearable in site.data.wearables %}
  {% if wearable['Support /<br>sensors'] contains 'YES' and wearable.Vendor == 'Samsung' %}
      * {{ wearable.Vendor }} - {{ wearable.Device}}
  {% endif %}
{% endfor %}

## Unsupported watches
NOTE: This list may not be exhaustive.

{% for wearable in site.data.wearables %}
  {% if wearable['Support /<br>sensors'] contains 'NO' and wearable.Vendor == 'Samsung' %}
     * {{ wearable.Vendor }} - {{ wearable.Device}}
  {% endif %}
{% endfor %}