---
layout: default
title: Smartwatches and Wearables
nav_order: 2
parent: /devices/0parent.html
no_troubleshooting: true
has_children: true
tags:
  - fitbit
  - samsung
  - xiaomi
  - mi band
  - garmin
---

== How to set up tracking with a wearable

. First of all, make sure your wearable is supported (see the <<supported_wearables, table>>)
. Install the required companion apps (this depends on the wearable type, check the <<supported_wearables, table>>) for more details).
. Select the corresponding option in _Settings -> Wearables -> Use wearable_.

NOTE: Sleep tracking collects data the whole night and they are analyzed in real-time. This means the watch must stay connected with BT during sleep tracking.

== Supported wearables[[supported_wearables]]

Sleep as Android supports a wide variety of smartwatches. Take a look at the list:

.Legend for sensor

[horizontal]
↝:: Movement detected from the wearables' accelerometer
❤:: Heart rate (HR)
💟:: Heart rate variability (HRV) - all models from the category with this sensor
◌:: Blood oxygen saturation (SpO2) - all models from the category with this sensor


|===
|Manufacturer |Device |Supported sensors |Notes


{% for wearable in site.data.wearables %}
  {% if wearable['Support /<br>sensors'] contains 'YES' %}

| +++ {{ wearable.Vendor }} +++
| +++ {{ wearable.Device }} +++
| +++ {{ wearable['Sensors supported'] }} +++
| +++ {{ wearable['Notes'] }} +++

  {% endif %}
{% endfor %}

|===
