---
layout: default
title: Smartwatches and Wearables
nav_order: 2
parent: /devices/0parent.html
no_troubleshooting: true
has_children: true
tags:
  - fitbit
  - samsung
  - xiaomi
  - mi band
  - garmin
---
:toc:


== How to set up tracking with a wearable

. First of all, make sure your wearable is supported (see the <<supported_wearables, table below>>).
. Check if the wearable is connected properly via Bluetooth.
. Install the required companion apps - this depends on the wearable type, check the <<supported_wearables, table below>>, or one of the subpages.
. Select the corresponding option in _Settings -> Wearables -> Use wearable_.
. You can test the connection on some wearables with the Test sensor - see <</devices/test_sensor, details about testing the connection here>>.

You can find specific guides for each wearable type on the subpages of the Wearable section.

NOTE: Sleep tracking collects data the whole night and the data are analyzed in real-time. This means the watch must stay connected with BT during sleep tracking.

== Supported wearables[[supported_wearables]]

Sleep as Android supports a wide variety of smartwatches. Take a look at the list:

.Legend for sensors

[horizontal]
↝:: Movement detected from the wearables' accelerometer
❤:: Heart rate (HR)
💟:: Heart rate variability (HRV) - all models from the category with this sensor
◌:: Blood oxygen saturation (SpO2) - all models from the category with this sensor


|===
|Manufacturer |Device |Supported sensors |Notes


{% for wearable in site.data.wearables %}
  {% if wearable['Support /<br>sensors'] contains 'YES' %}

| +++ {{ wearable.Vendor }} +++
| +++ {{ wearable.Device }} +++
| +++ {{ wearable['Sensors supported'] }} +++
| +++ {{ wearable['Notes'] }} +++

  {% endif %}
{% endfor %}

|===


== Guide

=== Create an alarm only as vibrations on watch (no sound, delayed sound)

. Set the alarm silent (_<<per-alarm,Alarm-specific settings>> -> Ringtone -> Silent_) or set the delay on sound (_Settings -> Alarms -> Sound delay_).
. Enable wearable vibrations (_Settings -> Wearables -> Vibrate_).
+
NOTE: We highly recommend to set a sound delay instead of setting the alarm silent, especially when backup alarm is silent too.