---
layout: default
title: Wear OS devices
nav_order: 4
parent: /devices/wearables.html
tags:
- wearos
- wearable
---

Sleep tracking with Wear OS device requires a companion app installed from the Play Store on the watch.

All Wear OS devices can monitor sleep tracking movement and collect HR.

Some wearables can also collect SpO2 data - for more details, please see the chapter on <</devices/oximeter#, oximeters and SpO data>>. Currently, Ticwatch Pro 3, Ticwatch E 3, and Fossil Gen 6, have integrated SpO2 data.
If you have a Wear OS-based wearable with Spo2 sensor, that is not on the list, please let us know. We can adjust the parameters and integrate the sensor on other watches too.

.Supported versions of OS

* Android Wear 1.0
* Wear OS 2.0
* Wear OS 3.0 (with some limitations)

WARNING: Wear OS 3.0 have some impletemented limitations for independent apps:
- not all wearables allow reading SpO2 or HRV data (Pixel Watch for example)
- Bedtime mode will NOT allow vibrations for alerm

== How to set up

. Make sure the watch is connected to the phone.
. Go to app list on your watch, select Play Store.
. Find *Sleep as Android* and select _Install_.
. After the companion app is installed, you can enable the connection in _Settings -> Wearables -> Use wearable -> Wear OS_.
. Test the connection in Settings -> Wearables -> Test sensor - you should see a graph reacting to your movement (a short delay is normal, data are sent in batches).
. For HR data, enable *Heart rate monitoring* in _Settings -> Wearables_.


