---
layout: default
title: Alarm settings
nav_order: 2
parent: Alarms
---

:toc:

== What it does
Alarm definition: an anxious awareness of danger :) TODO text

NOTE: for even better experience with alarms, see also Smart wake up ([red]TODO ikona a lepší text)

== Where to find it
._Sleep as Android > Settings > Alarm default settings_
Default settings allows you to modify behaviour for all your alarms. Default settings are applied to all new alarms, unless you change the per-alarm settings.
or
._per-alarm settings_
Per-alarm settings change behaviour of a specific alarm; those changes won't affect other alarms or default settings.


== Options
[horizontal]
Ringtone:: See Ringtone TODO
Snooze:: See Snooze TODO
Backup alarm:: See Backup alarm TODO
Alarm timeout:: See Backup alarm TODO
Alarm output:: Can force the alarm sound output to headphones only


== Advanced Options
[horizontal]
Gentle volume increase:: alarm starts at minimum volume and gradually increase
* Disabled - alarm starts at set volume
* 1-24 minutes - sets how long it takes to reach the set volume (~ speed of the increase)
Vibrate:: enables phone vibrations
* Disabled - no vibrations at all
* From start - vibrations start at alarm time
* After 1-24 minutes - sets a delay for vibrations
Alarm sound start::
* From start - sound start at alarm time
* 1-24 minutes - sets a delay for sound
Play alarm in silent profile:: enables to trigger alarm in silent mode
Flip to snooze:: lets you snooze an alarm by flipping the phone
Volume or camera button effect:: allows to snooze or dismiss the alarm with volume buttons
No screen orientation changes:: prevents changes of screen orientation while the alarm rings
Long press:: long press on dismiss button is necessary to turn the alarm off (prevents accidently dismissed alarms)

== Per-alarm settings
same as for alarm default settings, except for some new options
[horizontal]
Repeat:: sets a schedule for repeating alarm, you can choose also Even/odd pattern (TODO odkaz na Guide)
Silent alarm (in Ringtone):: - sets alarm without sound
Delete after ringing:: deletes this alarm completely after dismiss
Terminate tracking:: allows you to continue with tracking after alarm dismiss


NOTE: for even better experience with alarms, see also Smart wake up (<span style="color:red">TODO ikona a lepší text</span>)

== Guide
[horizontal]
Create vibrations only alarm (no sound)::
. Set the alarm silent (*per-alarm settings > Ringtone > Silent*) or set the delay on sound (*Settings > Alarm default setting > Sound delay*)
. Enable vibrations (*Settings > Wearables > Vibrate*)
NOTE: We highly recommend to set a sound delay instead of setting the alarm silent, especially when backup alarm is silent too.
Postpone or skip next alarm::
. Open alarm > Postpone next alarm / Skip Next
NOTE: Works only for repeated alarms
Dismiss alarm before alarm time::
. Open before alarm notification (appears one hour before alarm)
. Dismiss from the notification
NOTE: won't deactivate the alarm completely, so it has no effect on next alarms

Use my own sound as alarm::
. Open Ringtone selection: _Settings > Alarm default settings > Ringtone_ or _per-alarm settings > Ringtone_
. Tap on folder (TODO) icon
. Choose a sound file saved on your phone
Name an alarm::
. Open per-alarm settings or create new alarm dialogue
. Name the alarm in the Label field
Create odd / even schedule::
. Open per-alarm settings
. Choose Repeat dialogue
. Choose Weekly / Even / Odd pattern

== Troubleshooting
[horizontal]
Alarms do not ring::
* Make sure no system restrictions are applied to Sleep as Android: link:https://dontkillmyapp.com/[Check our guide here]
* Send us your log using _Left ≡ menu > Report a bug_
Alarms play at max volume::
* Most probably your backup alarm went off after regular alarm did not wake you up
* Send us your log using _Left ≡ menu > Report a bug_
Silent alarms ring::
* When battery saving mode enabled, vibrations are not going off, so a sound alarm is played despite the settings to make sure you are waken up
* _Settings > Sleep tracking > Battery optimized_
* _Tracking screen > Stop and save pull up menu > Save battery_
Alarm rings before set alarm time::
* Smart alarm is enabled
* _Settings > Sleep tracking > Smart period_
Alarm sound is too quiet::
* Gentle volume increase is enabled or set for too long period
* _Settings > Alarm default settings > Gentle volume increase_
Alarms do not play the selected ringtone::
* Loading of the selected file has failed
* Re-select the ringtone and make sure the app has permission to external storage
Only the first created alarm goes off::
* When multiple alarms are created close together, they might overlap each other
Alarms go off one hour late (59 minutes)::
* Power nap feature is chosen as your smart period
* *Settings > Sleep tracking > Smart wake up > Smart period*