---
layout: default
title: Alarm settings
nav_order: 2
parent: /docs/alarms
tags:
  - alarm
---
:toc:

== What it does
*Adjust alarms to best fit your lifestyle.*

NOTE: For even better wakeup experience, see also link:../alarms/smart_wake_up.html[Smart wake up]

== Where to find it
Alarms can be modified at two places - for a specific alarm in _per-alarm settings_, and for all alarms in _Alarm default settings_.

._Per-alarm settings_
Per-alarm settings change behaviour of a specific alarm; those changes won't affect other alarms or default settings.

._Sleep as Android -> Settings -> Alarm default settings_
Alarm default settings allow you to modify basic behaviour for all your alarms. Default settings are also applied to all new alarms.

== Options

[horizontal]
Ringtone:: See link:../alarms/ringtone.html[Ringtone].
Gentle volume increase:: Alarm starts at minimum volume and will gradually increase to maximum.
* Disabled - Alarm rings at volume set in link:../alarms/ringtone.html[Ringtone] section.
* 1-24 minutes - Sets how long it takes to reach the max volume; the longer the period, the slower the volume increases and the longer it takes to reach the max.
Vibrate:: Enables phone vibrations (do not confuse with vibrations on wearable).
* Disabled - No vibrations on phone at all.
* From start - Vibrations start at alarm time.
* After 1-24 minutes - Vibrations start after set time.
Alarm sound start::
* From start - Sound starts at alarm time.
* 1-24 minutes - Sounds starts after set time.
Play alarm in silent profile:: Alarm sound will override phone's silent mode.

.Snooze / Dismiss
[horizontal]
Snooze:: See link:../alarms/snooze.html[Snooze].
Always fullscreen alarm:: Alarm will never show up as a heads-up notification. This is especially useful from Android 10 where the notification might not show at all sometimes.
Flip to snooze:: Lets you snooze an alarm by flipping the phone.
Volume or camera button effect:: Allows to snooze or dismiss the alarm with volume buttons.
No screen orientation changes:: Prevents changes of screen orientation while the alarm rings.
Long press:: Long press on dismiss button is necessary to dismiss the alarm (prevents accidentally dismissed alarms).

.Backup alarm
[horizontal]
Backup alarm:: See link:../alarms/backup.html[Backup alarm].
Alarm timeout:: See link:../alarms/backup.html[Backup alarm].

.Dangerous options
[horizontal]
Alarm output:: Can force the alarm sound output to media stream, so the alarm is audible only in your headphones.
NOTE: Please, test it before using it - some vendors do not allow to use media stream for alarms!
Alarm reliability:: Can increase reliability of the alarm on problematic phones (see https://dontkillmyapp.com?app=Sleep%20as%20Android[dontkillmyapp.com]).

.Per-alarm settings
Same as for alarm default settings; a few different options are available, listed below.
[horizontal]
Repeat:: Set a schedule for repeating alarm, you can choose also <<even_odd,Even / odd pattern>>.
Delete after ringing:: Deletes this alarm completely after dismiss.
Terminate tracking:: Allows you to continue with tracking after alarm dismiss.
Silent alarm (in Ringtone):: Sets alarm without sound.

== Guide
[horizontal]
Create alarm only as vibrations on watch (no sound)::
NOTE: We highly recommend to set a sound delay instead of setting the alarm silent, especially when backup alarm is silent too.
. Set the alarm silent (_per-alarm settings -> Ringtone -> Silent_) or set the delay on sound (_Settings -> Alarm default setting -> Sound delay_).
. Enable wearable vibrations (_Settings -> Wearables -> Vibrate_).

Create silent alarm::
NOTE: We highly recommend to set a sound delay instead of setting the alarm silent, especially when backup alarm is silent too.
. Set the alarm silent (_per-alarm settings -> Ringtone -> Silent_).
. This option is available only in per-alarm settings, not in Alarm default settings.
Postpone next alarm::
NOTE: Works only for repeating alarms.
. Open alarm -> Postpone next alarm.
. Use the sliding bar or the drop down menu list for postponing alarm.
. Confirm the alarm time change.
Skip next alarm::
NOTE: Works only for repeated alarms.
. Open an alarm -> Skip next, confirm the change.
. Or long press on the alarm on alarm board -> Skip next.
Dismiss alarm before alarm time::
NOTE: won't deactivate the alarm completely, so it has no effect on next alarms.
. Open before alarm notification (appears one hour before alarm) from the notification bar on your phone.
. Dismiss from the notification.
Use my own sound as alarm::
. Open Ringtone selection: _Settings -> Alarm default settings -> Ringtone_ or _per-alarm settings -> Ringtone_.
. Tap on folder (TODO) icon in right upper corner.
. Choose a sound file saved on your phone.
Name an alarm::
. Open an alarm settings or create new alarm dialogue.
. Name the alarm in the Label field in upper right corner.
Create odd / even schedule:: [[even_odd]]
. Open per-alarm settings.
. Choose Repeat dialogue (_Repeat:Never_ or days of week listed below alarm time).
. Choose Weekly / Even / Odd pattern from the drop down menu list.
