---
layout: default
title: Backup alarm
nav_order: 2
parent: Alarms
---

:toc:

== What it does

Starts ringing loudly on maximum volume if you ignore your normal alarm.

// TODO: banana

== Where to find it
_Sleep as Android -> Settings -> Alarm default settings -> Backup alarm_

NOTE: If you want to disable the backup alarm functionality, set it to Silent ringtone (see TODO:)

== Options
[horizontal]
Backup alarm duration:: Sets for how long will the backup alarm ring (after that it gets snoozed – it will ring again after a regular alarm timeout)
Ringtone:: Selects the backup ringtone, or sets the ringtone as silent
Alarm timeout:: Sets the time after which the backup alarm will ring if you ignore your normal alarm.
Repeat:: Sets how many times the backup alarm will repeat – after that, no alarm rings anymore.

EXAMPLE:: Alarm time: 7:00
Backup alarm duration: 2 minutes
Alarm timeout: 10 minutes
This is what happens when you don’t interact with the alarm
7:00 – alarm starts
7:10 – backup alarm starts (full volume, duration 2 min)
7:12 – automatically snoozes (for 10 minutes)
7:22 – backup alarm starts again
…
…and so on, based on the number of repeats.
