---
layout: default
title: Backup alarm
nav_order: 2
parent: Alarms
---

:toc:
= Backup alarm

== What it does
The backup alarm starts playing at max volume after a period of not interacting with the alarm.

NOTE: If you want to disable the backup alarm functionality, set it to Silent ringtone (see TODO)

== Where to find it
_Sleep as Android > Settings > Alarm default settings > Backup alarm_

== Options
[horizontal]
Backup alarm duration:: sets for how long will the backup alarm ring (after that it gets snoozed – it will ring again after a regular alarm timeout)
Rintone:: selects the backup ringtone, or sets the rintone as silent
Alarm timeout:: sets the time after which the backup alarm will ring if You ignore Your normal alarm.
Repeat:: sets how many times the backup alarm will repeat – after that, no alarm rings anymore.

NOTE: Alarm time: 7:00
Backup alarm duration: 2 minutes
Alarm timeout: 10 minutes
This is what happens when You don’t interact with the alarm
7:00 – alarm starts
7:10 – backup alarm starts (full volume!!, duration 2 min)
7:12 – automatically snoozes (for 10 minutes)
7:22 – backup alarm starts again
…
…and so on, based on the number of repeats.
