---
layout: default
title: Bedtime notification
nav_order: 2
// parent: /docs/alarms
---
:toc:

## What it does
*Sends you a "Time to go to bed!" notification slightly before bedtime.*

Bedtime notification is an effective way to maintain optimal sleep length or fight high sleep deficits. You can set the notification to trigger between 5 minutes to 2 hours before bedtime so you'll have enough time to prepare for bed.

[NOTE]
====
The time to trigger the notification is calculated as follows:
`bedtime = next alarm time – ideal daily sleep income`

.Example:
You've set _ideal daily sleep income_ to 7 hours, and an alarm for 6 AM.
Your bedtime would be 11 PM.
====

== Where to find it
_Settings -> Bedtime notification_


== Options
[horizontal]
Ideal daily sleep income:: Set how much time would you ideally want to sleep each night.
Bedtime notification:: Enable bedtime notification and set how long before bedtime to receive it.
Repeat:: How often should the notification repeat
  - Example: 10 minutes repeat will notify you once on notification time and then every 10 minutes until you swipe the notification away or start sleep tracking
Smart bedtime::
  When enabled, smart bedtime adjusts the notification time according to your sleep deficit for the last 5 days, average length of the smart wake up period, and default pause at the beginning of sleep tracking

  `smart time to bed = next alarm – ideal daily sleep income – smart period – delayed tracking – in(5 days avg. sleep deficit > 10 min, 45 min)`