---
layout: default
title: Captcha
nav_order: 2
parent: Alarms
---

:toc:

== What it does

CAPTCHA is another very effective tool in preventing oversleeping - a little task which needs to be solved first before the alarm gets dismissed.
Prove you are a human even though you sleep as android!

== Where to find it

_Settings > CAPTCHA: Stop oversleeping!_
_per-alarm settings > CAPTCHA: Stop oversleeping!_
NOTE: CAPTCHA can also be configured per alarm, so you can override your CAPTCHA settings and use a different CAPTCHA with more difficult settings on special occasions (e.g. exams) or easier CAPTCHA on the weekends

== Options
[horizontal]
Default CAPTCHA::
 Simple math:: select the correct answer
 Typed math:: write the correct answer
 Sleeping sheep:: find an awake sheep
 QR code:: see TODO
 NFC tag:: see TODO
 Shake it::  shake your phone
 Dream diary:: write down your dreams (10 characters minimum at Difficulty 1)
 Say cheese!:: smile to your front camera
CAPTCHA Difficulty:: allows you to set a difficulty, the more difficult the task, the more repetition of that task
Preview:: shows you the task in advance
Settings:: edits some of the tasks settings
 * editing, adding and deleting QR codes and NFC tags
 * selecting tasks for MultiCaptcha
 * choosing your mantra for Mirror Text
CAPTCHA ADD-ons:: download free extension with more Captcha tasks
 Captcha Captcha:: type the letters of a distorted image
 Random Captcha:: solve up to 5 different tasks each morning
 Multi Captcha:: solve up to 15 chosen tasks in a row
 Mirror text:: reade and type a text from a flipped quote
 Swearing:: swear your way to dismiss (English only)
 Zombie Walk:: walk 14-74 meters with the phone
 Let there be light:: put your phone to a light source
 Fun with Flags:: recognize flags
 Spin around:: spin around while keeping thumbs on the buttons on the screen

== Advanced Options
[horizontal]
Alarm volume in CAPTCHA:: lowers or mute the alarm volume while solving a task
Prevent escaping CAPTCHA:: prevents you to force closing or uninstalling the app

NOTE: During CAPTCHA solving, alarm volume is lowered for 2 minutes so that you don’t wake your partner with the ongoing alarm. You can use the 2 minutes either to solve the CAPTCHA or get to a different room for solving.
To get more time to solve your task, tap on + icon

== QR code and NFC tag CAPTCHA

The QR and NFC CAPTCHAs are the ultimate solution for waking up. You can place a QR code or NFC tag in your bathroom or kitchen. The alarm than won’t stop until you get out of bed and scan the code/tag.

[horizontal]
QR CAPTCHA:: You can use any barcode or QR code (there are many free online QR code generators).
Supported QR apps: Barcode Scanner, QRDroid, Google Goggles
NFC CAPTCHA:: You can use any credit card, some membership cards or ID cards
For security reasons, NFC Captcha requires unlocking the screen
Only at home:: allows you to skip CAPTCHA when not at home
Must scan all codes:: you need to scan all saved codes

=== Guide for QR and NFC Captcha
[horiznotal]
Learn new QR code / NFC tag::
. Go to _Settings > Captcha > Settings_
. Tap on "Learn"
Delete a code / tag::
. Go to _Settings > Captcha > Settings_
. tap on TODO (ikona)


== Troubleshooting

* Cannot find settings for one Captcha when MultiCaptcha is selected