---
layout: default
title: Create alarm
nav_order: 2
parent: /docs/alarms
---

:toc:

== What it does

.Create alarm allows you to create a new alarm or a nap.

== Where to find it

New alarms are created using the TODO: icon

To quickly edit an existing alarm, tap on the time of the alarm.

TODO: obrázek

== Options

[horizontal]
Time picker:: You can choose between round clock time picker (default) and Analogue time picker (must be enabled in _Settings -> Miscellaneous_).
Voice:: Use TODO icon and then say the time aloud, Google speech recognition will recognize the time and use it.
Keyboard:: Use the TODO button and type the time in HHMM format.
Wake up at the next sunrise:: Use the TODO button, the alarm is scheduled for the sunrise (location permission is needed).
Wake up at an ideal time:: Tap on the *Ideal* button. The time is scheduled for reaching your Ideal daily sleep income (set is _Settings_)

//== Guide
// Free form description on how to use the feature, various quirks and best practices