---
layout: default
title: Ringtone
nav_order: 2
parent: /docs/alarms/alarms.html
tags:
- ringtone
---
:toc:

== What it does
*Change the sound of alarm(s) to any pleasant music of your choice for even more enjoyable mornings.*

== Where to find it
_Settings -> Alarm default settings -> Ringtone_

== Options

[horizontal]
Silent:: Available only in settings of each specific alarm (per-alarm), won't turn off vibrations.
Single ringtone:: Choose any option from the list.
Alarm sound from the list:: Choose any option from the list.
Any sound file:: Tap on the folder icon and select your chosen file.
Own Playlist:: Tap on double check mark and choose files to create a playlist (TODO odkaz na Guide).
Spotify playlist:: You can add your saved albums or playlists from Spotify’s _Your Library > Albums / Playlists_
Other playlists (including link:/faqs/google_play_music.html[Google Play Music] playlists):: Lots of media player apps can create such playlists from music that is available on your phone.
File-based playlists:: You can use any file-based playlist (.m3u, .pls) you have on your phone.

== Guide

[horizontal]
How to create your own playlist::
. Open Ringtone selection and tap on the TODO icon in the upper right corner.
. Now select any combination of the available ringtones.
. Choose the order (Shuffle / Order / Loop single) in the ⋮ menu in upper right corner.
. Confirm the selection with "OK" button or TODO icon.
How to add my own song, sound file::
. Tap on the folder TODO icon in the upper right corner.
. Select a file in your file browser
. Make sure the file is available and the app has permission for accessing that folder.
