—
layout: default
title: Smart wake up
nav_order: 2
parent: Alarms
---

= Smart Wakeup

== What it does
Smart wake up sets a window prior to alarm time and finds the optimal moment to wake you in light sleep phase.

TIP: You can use a longer smart period for weekends and shorter period for workdays

Curious whether it really works? Check our global study of smart alarm use the <span style="color:red">TODO link nebo i link na více teorie?</span> button!

*Example* Alarm time: 8:00
Smart period: 30 minutes (default)
Sleep as Android will wake you between 7:30-8:00, once you are in light sleep for some time. The scheduled alarm time (8:00) is considered as the last possible wake up time.


== Where to find it
*Settings > Sleep tracking > Smart wake up*
*per-alarm settings > Smart wake up*

== Options
[horizontal]
Smart period:: sets a smart period before alarm time
Nap smart period:: sets a smart period before alarm time for naps with tracking and naps from shortcuts

== Advanced options
[horizontal]
Movement intensity:: modifies sensitivity of the inititating alarm during smart period
Movement occurence:: modifies sensitivity of the inititating alarm during smart period
Not before ideal sleep:: does not allow the alarm before reaching either alarm time or ideal sleep duration

== Guide
// Free form description on how to use the feature, various quirks and best practices

==Troubleshooting
[horizontal]
Alarms go off exactly at the beginning of smart period::
. Lower the sensitivity of Smart wakeup in *Settings > Sleep tracking > Movement intensity* or *Movement occurance*
Alarms go off only at alarm time at the end of smart period::
. Increase the sensitivity of Smart wakeup in *Settings > Sleep tracking > Movement intensity* or *Movement occurance*

= Power Nap

== What it does
Power nap is a special case of smart wake up for situations when you don’t have a maximum time when you need to be woken up, but you prefer sleep a given time for sure and then finish one whole sleep cycle afterward.

*Example* Let say it is weekend and you can wake up any time after 10:00. You will schedule a power nap alarm for 10:00 which will look for the best moment to wake you up between 10:00-11:00
You can do a nap of minimum 20 minutes but keep Sleep as Android find you best moment afterward so power nap will make sure you sleep at least 20 minutes and find the best moment in 20+59 minutes.

== Where to find it
*Settings > Sleep tracking > Smart wakeup > Smart period*
or
*per-alarm setings > Smart period*