---
layout: default
title: Smart wakeup
nav_order: 2
parent: Alarms
---

:toc:

== What it does
.Smart wake up sets a window before the alarm time and finds the optimal moment to wake you up in light sleep phase.

Curious whether it really works? Check our https://sleep.urbandroid.org/a-case-for-the-smart-alarm/[global study of smart alarm.]

TIP: You can use a longer smart period for weekends and shorter period for workdays

NOTE: Alarm time: 8:00
Smart period: 30 minutes (default)
Sleep as Android will wake you between 7:30-8:00, once you are in light sleep for some time. The scheduled alarm time (8:00) is considered as the last possible wake up time.


== Where to find it
_Settings -> Sleep tracking -> Smart wake up_

== Options
[horizontal]
Smart period:: sets a smart period before alarm time
* Disabled - alarm goes off at alarm time exactly
* Power nap - special type of smart period, see link:../alarms/power_nap.html[power nap]
* 5 minutes - 2 hour - alarm goes of during the selected period prior to alarm time
Nap smart period:: sets a smart period for naps with tracking and naps from shortcuts
* Disabled - alarm goes off at alarm nap time
* Power nap - special type of smart period, see link:../alarms/power_nap.html[power nap]
* 5 minutes - 2 hour - alarm goes of during the selected period prior to alarm time

== Advanced options
[horizontal]
Movement intensity:: Modifies sensitivity of the initiating alarm during smart period. Higher sensitivity will trigger alarm
Movement occurrence:: Modifies sensitivity of the initiating alarm during smart period
Not before ideal sleep:: Does not allow the alarm before reaching either ideal sleep duration or alarm time. This option can lead to ignoring the smart period fr the sake of reaching sleep duration closest to ideal sleep duration.

== Guide
// Free form description on how to use the feature, various quirks and best practices
