---
layout: default
title: Snooze
nav_order: 2
parent: /docs/alarms
---
:toc:

== What it does
*Snoozes delay your wake up if you do not yet feel rested on alarm time.*

After hitting a snooze button on alarm screen, you get an additional period of sleep, and alarm time is postponed.
You can also limit the snoozing to prevent oversleeping.

== Where to find it
* _Settings -> Alarms -> Snooze_
* link:/docs/alarms/alarm_settings.html#per-alarm[Per-alarm settings]

== Options
[horizontal]
Snooze duration:: Default snooze time on alarm screen (the only one or the biggest button).
Snooze limit:: The maximum count of snoozes you are allowed. When this number is reached, you can only dismiss the alarm.
Maximum total snooze time:: The maximum time total you are allowed to snooze. When this total is reached, you can only dismiss the alarm.
Halve Snooze:: Each consecutive snooze duration is halved.
Changing snooze time:: Allows changing snooze duration on alarm screen during alarm (enables selection of different snooze durations).
Snooze after alarm time:: Snoozing may be completely disabled after the alarm time has been reached (works only for smart alarm)
EXAMPLE::If your alarm is set to 7:00 and due to smart wake-up it rings at 6:57, the longest possible snooze will be 3 minutes.[]
