---
layout: default
title: Snooze
nav_order: 2
parent: /docs/alarms
---

:toc:

== What it does
.Snoozes delay your wake up if you do not yet feel rested on alarm time.

After hitting a snooze button on alarm screen, you get additional period of sleep, and alarm time is postponed.
You can also restrict or limit the snoozing to prevent oversleeping.

== Where to find it
_Settings -> Alarm default settings -> Snooze_

== Options
[horizontal]
Snooze duration:: The main option of snooze on alarm screen (the only one or the biggest button).
Snooze limit:: The maximum count of snoozing you are allowed. When this number is reached, only dismiss button is on the alarm screen.
Maximum total snooze time:: The maximum time you are allowed to snooze. When this time is reached, only dismiss button is on the alarm screen.
Halve Snooze:: Each consecutive snooze duration is halved.
Changing snooze time:: Allows changing snooze duration on alarm screen during alarm (enables selection of different snoozes).
Snooze after alarm time:: Snoozing may be completely disabled after the alarm time has been reached (works only for smart alarm)
NOTE: If your alarm is set to 7:00 and due to smart wake-up it rings at 6:57, the longest possible snooze will be 3 minutes.

== Guide
// Free form description on how to use the feature, various quirks and best practices
