---
title: Customized vibrations on MiBands

tags:
- wearable
- vibration
- alarm
- miband
---

Vibration can be controlled only from the companion app, because the integration with MiBands is not direct (the API is not available for the integration).
Luckily, both companion apps allow vibration customization in the pro versions.

== Tools & MiBand
. Enable priority override mode for MiBand Tools app: pull down the notification bar, and on the MiBand Tools status bar notification, press the first icon multiple times, until you enter priority override mode = you will se an exclamation mark.
. In Mi Band Tools app: _Left_ ☰ _menu -> Settings -> Sleep as Android -> Custom vibration_ adjust the vibrations. You can set vibration count and length, and delay between vibrations.
. Test the resulting vibration pattern with _Test vibration_.

== Notify & Fitness
. Enable custom vibrations in Sleep as Android settings section.
. Open the vibration settings with the _Vibration_ button.
. Adjust the vibration pattern - you can change intensity and duration, and also vibration delay.
. Test the resulting vibration pattern with the Play button in the top right corner.