---
title: I have a new phone, and I would like to transfer all the data I collected so far

tags:
  - backup
---

There are four possible ways to transfer your data to a new devices:

== Google backup
Normally we use Google's backup feature if it is enabled in _System settings -> Privacy_.
After installing Sleep as Android on the new device, you will get all your settings, alarms, and other data. This assumes you install with a fast network connection enabled.

NOTE: You can opt-out from this system backup in _Settings -> Personalize -> Privacy -> Android app data backup.

[[csv_export]]
== Import / export in the app - manually
You can also perform a manual export/import process:

. Go to the _Left_ ☰ _menu -> icon:ic_cloud_upload[] Backup -> Export_.
. When the "Backup Successful" dialog appears, select the "Share" button.
. Now you can choose your email client and the backup zip file will be attached to the body of a new email.
. Send it to yourself.
. Open the email client on your new phone, open the email, and tap on the attachment.
. You will be asked what data you want to import - select all the types of data you want to import and send.

== Import / export in the app - sharing the file with Google Drive
Another easy way to migrate to a new device is to share Google Drive.

. Go to the _Left_ ☰ _menu -> icon:ic_cloud_upload[] Backup -> Export_.
. When the "Backup Successful." dialog appears, select the "Share" button.
. Choose Google Drive, and confirm.
. Then open Google Drive on your other device, and select the backup file.
. You will be asked which data you wish to import - select all types of data you wish to import, and submit.

== Sleep Cloud
You can use one of the cloud backup methods from the SleepCloud add-on. Please read more about <</services/backup_data#,Backup>>.