---
layout: default
title: Home screen
nav_order: 1
---
:toc:

## What it does
You can personalize your main screen of Sleep with three different home screen types.

*Dashboard* is the default home screen, presenting all options in cards. It is very customizable - you can choose which cards are active, and also pin your most favourite one at the top.

*Tabs home screen* displays alarm list as the main screen, all other options are available in tabs. You can choose which tabs are shown.

*Alarms* is a special, simplified  mode, when you are using only alarms and do not care about the tracking at all.
The main screen shows list of your alarms. This mode hides all sleep tracking related settings.

// [Optional] Longer text describing the feature

## Where to find it
_Left_ ☰ _menu -> Home screen section -> Dashboard / Tabs / Alarms_
//TODO text
// Where to find the feature's settings and other related settings used to enable the feature, optionally with description
// EXAMPLE: _Sleep as Android -> Settings -> Wearables -> Use wearables_

## Options

.Dashboard

[horizontal]
Alarm card:: Shows you the first next active alarm.
* Alarm card has a shortcut for creating a new alarm (TODO ikona a dopsat text).
* Alarm card has also a special function - you can skip next alarm, edit alarm or delete alarm directly from this card by long pressing on it.
//TODO obrázek!!
* Simple tapping on alarm time opens dialogue for changing the alarm time.
* Tapping on (TODO ikona) opens the dialogue for creating a new alarm
* Tapping on any other place of the card opens List of alarms (TODO odkaz)

News card:: Temporary card shown only during important events or with a crucial message.
Best of noises card:: Shows you the selection of the best sounds recorded last night.
* After tapping on this card, a player plays the file.
Sleep score card:: See link:../docs/theory/sleepscore.html[Sleep score].
* Tapping on this card opens Stats (see link:../docs/theory/statistics_charts.html[Stats])
Graphs card:: Shows the last graph of sleep sleep phases.
* Tapping on this card open the last graph (how to read graphs - TODO link, jestli něco bude)
Noise card::
Charts card:: Shows you graphs from the link:../docs/theory/statistics_charts.html[Charts section].
* You can swipe through the graphs, right ↔ left.
* Tapping on this card opens link:../docs/theory/statistics_charts.html[Charts section].
Advice card:: Shows the current advice.
* Tapping on this card opens link:../docs/theory/Advice.html[Advice section].
Shortcuts card:: A mini-board with shortcuts.
TODO obrázek
* Ideal sleep shortcut (TODO máme někde sekci na shortcuts?)
* Naps shortcuts
* + Add sleep shortcut
NOTE: You can create a shortcut (Add alarm, Nap, Ideal sleep, and Sleep tracking) for your main screen TODO odkaz
Add-on card::
* Tapping on this card opens TODO-link:../docs/theory/TODO.html[Add-on section].


.Tabs

[horizonatl]
Alarm tab:: Shows you the list of all alarms (see TODO odkaz)
Dashboard tab:: Lists all cards from Dashboard (see TODO odkaz) except Alarm card
Stats tab:: Shows the Stats from Stats section (from Left ☰ menu, see TODO odkaz)
Graphs tab:: Shows the list of graphs from Graph section (from Left ☰ menu, see TODO odkaz)
Noise tab::  Shows the list of noise recordings from Noise section (from Left ☰ menu, see TODO odkaz)
Add-ons tab:: TODO

.Alarms

.List of alarms

* All active alarms in the list have highlighted background TODO obrzák
* Repeating alarms highlights the next alarm with different font color TODO obrzák
* Active alarm shows you time left to your bedtime 12 hours prior to bedtime (TODO obrázek
* If any alarm has its own settings different from default settings, the alarm card shows you those special settings (TODO obrázek)
* Each alarm card has also a special function - by long pressing on any alarm card, you can Turn activate/deactivate the alarm, skip next alarm, edit alarm, copy alarm and its settings, or delete alarm.
//TODO obrázek!!
* Simple tapping on alarm time opens dialogue for changing time of the alarm
* Tapping on the toggle activate / deactivate the alarm
* TODO ikona creates a new alarm
* TODO ikona koš deletes all unused non-active alarms

[horizontal]
lkadbfklasdbf



// Describe all the feature's options, see other docs pages for formatting

// EXAMPLE:

// [horizontal]
// Smart wake up:: See link:../alarms/smart_wake_up.html[Smart wake up]
// Awake detection:: See [Awake detection]

// .Automatic sleep tracking
// [horizontal]
// Start sleep tracking:: Set to something other than _Manual only_ to enable automatic sleep tracking start.
// - More details: link:automatic_sleep_tracking.html[Automatic sleep tracking].
// Sleep time estimate:: Do you forget to track your sleep? Enable this to receive sleep length estimates in a notification every day without you doing anything.
// - On _Manual only_, you'll receive a notification that you have to confirm in order to create the sleep record
// - On _Save automatically_, the notification saves the sleep record for you automatically
// - More details: link:sleep_time_estimation.html[Sleep time estimation]

// EXAMPLE END

## Guide
[horizontal]
How to get rid off a card on Dashboard:: TODO
How to get a lost card back on Dashboard:: TODO
How to get rid off a tab on Tabs:: TODO
How to get a lost tab on Tabs:: TODO
How to pin a card to top position:: TODO


// Free form description on how to use the feature, various quirks and best practices
