---
layout: default
title: Left ☰ menu
nav_order: 1
---
:toc:

## What it does

Left ☰ menu is an expandable menu for easy navigation and quick access to features.
// [Optional] Longer text describing the feature

(TODO šlo by tam dodat i ty ikonky?)

## Where to find it

Tap ☰ icon in the upper right corner, and the menu is revealed.
//TODO obrázek???


// Where to find the feature's settings and other related settings used to enable the feature, optionally with description
// EXAMPLE: _Sleep as Android -> Settings -> Wearables -> Use wearables_

## Options

.Chronotype
(TODO text, plus ikonka a odkaz na vysvětlení)



.Shortcuts

Available only in Tabs home screen mode.


[horizontal]
Ideal sleep::
Nap::
+ Add sleep::
Add alarm::


.Sleep as Android

[horizontal]
Alarms:: Opens List of alarms (TODO odkaz)
Stats::
Graphs::
Charts::
Advice::
Goal::
Noise::
Add-ons::
Backup::
Lullaby::
Settings:: ..

.Home screen

See TODO odkaz

[horizontal]
Dashobard:: See (TODO odkaz)
Tabs:: See (TODO odkaz)
Alarms:: See (TODO odkaz)


.Contact support

[horizontal]
Tutorial:: Opens a short introduction tutorial.
Documentation:: Opens you documentations (TODO odkaz na list of contents?)
Tell friends:: You can tell your friends about your experience with Sleep as Android (more about sharing - TODO odkaz na Share, pokud máme)
Release notes:: Get informed about latest changes in Sleep and new added features!
Report a bug:: Generates an application log, that can be shared with our support team to help you with any issue. Do not hesitate and tell us, what is now working properly, so we can fix it!
Send a wearable report:: Generates a special application log for debugging troubles with some wearables.
Terms of use:: You can read terms of use here - if you have any question or doubts, please contact us at support@urbandroid.org (TODO jde z toho udělat create email odkaz?)


// Describe all the feature's options, see other docs pages for formatting

// EXAMPLE:

// [horizontal]
// Smart wake up:: See link:../alarms/smart_wake_up.html[Smart wake up]
// Awake detection:: See [Awake detection]

// .Automatic sleep tracking
// [horizontal]
// Start sleep tracking:: Set to something other than _Manual only_ to enable automatic sleep tracking start.
// - More details: link:automatic_sleep_tracking.html[Automatic sleep tracking].
// Sleep time estimate:: Do you forget to track your sleep? Enable this to receive sleep length estimates in a notification every day without you doing anything.
// - On _Manual only_, you'll receive a notification that you have to confirm in order to create the sleep record
// - On _Save automatically_, the notification saves the sleep record for you automatically
// - More details: link:sleep_time_estimation.html[Sleep time estimation]

// EXAMPLE END

## Guide
// Free form description on how to use the feature, various quirks and best practices

