---
layout: default
title: Personalize
nav_order: 2
// parent: /docs
---
:toc:

== What it does
*Allows you to choose color of the graphs, theme, sort your alarms... and much more.*

== Where to find it

_Settings -> Personalize_

== Options

[horizontal]
Home screen:: Choose a type of link:..docs/homescreen[Home screen].
Theme:: You can choose a theme (background color of the app):
* Automatic (Android OS) - Follows your system settings.
* Automatic (Bedtime) - Uses dark theme between bedtime and sunrise.
* Night owl - Dark theme (black background, white font) all the time.
* Morning lark - Light theme (white background, black font) all the time.
Color palette (Graphs):: You can choose 7 different color palletes for your graphs:
* Default - The current default on new installations (a color may vary!).
* Theme - 50 Shades of Sleep...
* Green - Yoda green forever!
* Blue - Feeling blue?
* Purple - Been born in the purple?
* Miscellaneous - A combination of blue, teal, and yellow, to match your colorful personality.
* Legacy - Original graph palette from the good old times.
Text to speech:: If enabled, Sleep will tell you when it’s time to go to bed, wish you goodnight when you start sleep tracking, tell you it’s time to wake up when the alarm rings, and tell you weather in the morning, after you dismiss the alarm.


.Localization
[horizontal]
Force English:: Set app language to English, regardless of your system locale.
Temperature:: Choose temperature units for weather:
- °C
- °F
Start week on:: Choose which day is the first day of a week:
- Device default - the app follows your system locale.
- Sunday
- Monday

.Alarms
[horizontal]
Alarm sorting:: Sort alarms in alarm list based either on time or day. Default: Day. By setting Time, all your alarms will be sorted by time regardless on which day are they scheduled to ring.
Analog time picker:: A round analog clock time picker will be shown when creating new alarms instead of the digital one.

.Advanced
[horizontal]
Release notes:: If disabled, you won't be seeing release notes card/dialog when Sleep is updated to a new version. To check the release notes at will, tap _Left ☰ menu -> Release notes_.
Show advanced settings:: All advanced Settings are expanded on all settings screens.
Hide droid avatar:: Hides the Droid on the home screen.

