on: push

name: Publish Website

jobs:
  build-and-deploy:
    name: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      # Updated from @v2 to @v4 to fix the Node.js error
      - uses: actions/checkout@v4

      - name: Build
        uses: urbandroid-team/jekyll-build-action@8

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./_site/
